#!/usr/bin/env python3
"""Deterministic verifier for task SpotHero--5 (generated by make_verifiers.py).

Ground truth is frozen from the reviewer's independent computation and live
honest walks on the review container (seed md5 482fb61d…). See
verify/README.md for the contract and task-specific caveats.
"""
import sys

from verify_lib import (Judge, check_package, check_seed_contract,
                        check_visited_path, check_visited_path_count,
                        check_answer_phrase,
                        check_answer_number, check_answer_any_number,
                        check_answer_any, check_only_tables_changed,
                        check_reservations_delta, check_any_new_reservation,
                        check_payment_methods_delta, check_profile_delta,
                        check_favorites_delta, check_new_user, final_answer,
                        run_verifier)

TASK_ID = "SpotHero--5"


def main(judge, traj, initial_db, after_db):
    answer = final_answer(traj)
    check_package(judge, traj, TASK_ID)
    check_seed_contract(judge, initial_db)
    check_visited_path(judge, traj, "login", r"/auth/login")
    check_visited_path(judge, traj, "airport_reservation", r"/account/reservations/SH-6N9WF4")
    check_visited_path(judge, traj, "ord_airport_page", r"/airport/chicago-ord-parking|/airport-code/ORD")
    check_visited_path(judge, traj, "ord_search", r"/search\?kind=airport.*airport=ORD")
    check_visited_path(judge, traj, "booked_lot_page", r"/facility/152325")
    check_visited_path(judge, traj, "checkout", r"/purchase/hourly\?facility=152325")
    check_visited_path(judge, traj, "confirmation", r"/purchase/confirmation/SH-")
    check_answer_phrase(judge, answer, "refund_message", '5-10 business days')
    check_answer_phrase(judge, answer, "booked_lot_named", 'Courtyard by Marriott Wood Dale')
    check_answer_number(judge, answer, "new_total", '52.00')
    check_reservations_delta(judge, initial_db, after_db, answer,
                             expect_added={'facility_id': 152325, 'kind': 'airport', 'total': 52.0, 'email': 'david.k@test.com', 'starts': '2026-10-10T12:00', 'ends': '2026-10-14T12:00', 'promo': '', 'user_id': 4, 'status': 'upcoming', 'parking_pass': 'Monitored by License Plate'},
                             expect_updated={'SH-6N9WF4': {'status': 'cancelled'}})
    check_only_tables_changed(judge, initial_db, after_db, ('reservations',))
    return judge


if __name__ == "__main__":
    sys.exit(run_verifier(TASK_ID, main))
