#!/usr/bin/env python3
"""Deterministic verifier for task SpotHero--3 (generated by make_verifiers.py).

Ground truth is frozen from the reviewer's independent computation and live
honest walks on the review container (seed md5 482fb61d…). See
verify/README.md for the contract and task-specific caveats.
"""
import sys

from verify_lib import (Judge, check_package, check_seed_contract,
                        check_visited_path, check_visited_path_count,
                        check_answer_phrase,
                        check_answer_number, check_answer_any_number,
                        check_answer_any, check_only_tables_changed,
                        check_reservations_delta, check_any_new_reservation,
                        check_payment_methods_delta, check_profile_delta,
                        check_favorites_delta, check_new_user, final_answer,
                        run_verifier)

TASK_ID = "SpotHero--3"


def main(judge, traj, initial_db, after_db):
    answer = final_answer(traj)
    check_package(judge, traj, TASK_ID)
    check_seed_contract(judge, initial_db)
    check_visited_path(judge, traj, "ord_airport_page", r"/airport/chicago-ord-parking|/airport-code/ORD")
    check_visited_path(judge, traj, "ord_search", r"/search\?kind=airport.*airport=ORD")
    check_visited_path(judge, traj, "mdw_airport_page", r"/airport/chicago-mdw-parking|/airport-code/MDW")
    check_visited_path(judge, traj, "mdw_search", r"/search\?kind=airport.*airport=MDW")
    check_visited_path(judge, traj, "cheaper_lot_page", r"/facility/152325")
    check_visited_path(judge, traj, "checkout", r"/purchase/hourly\?facility=152325")
    check_visited_path(judge, traj, "confirmation", r"/purchase/confirmation/SH-")
    check_answer_phrase(judge, answer, "winning_airport", "O'Hare")
    check_answer_phrase(judge, answer, "ord_lot_named", 'Courtyard by Marriott Wood Dale')
    check_answer_number(judge, answer, "ord_per_day", '12.00')
    check_answer_number(judge, answer, "mdw_per_day", '13.00')
    check_answer_number(judge, answer, "total", '40.00')
    check_answer_phrase(judge, answer, "first_step", 'Enter this location at 900 N Wood Dale Rd')
    check_reservations_delta(judge, initial_db, after_db, answer,
                             expect_added={'facility_id': 152325, 'kind': 'airport', 'total': 40.0, 'email': 'ord.flyer@example.com', 'starts': '2026-10-03T12:00', 'ends': '2026-10-06T12:00', 'promo': '', 'user_id': None, 'status': 'upcoming', 'parking_pass': 'Monitored by License Plate'},
                             expect_updated=None)
    check_only_tables_changed(judge, initial_db, after_db, ('reservations',))
    return judge


if __name__ == "__main__":
    sys.exit(run_verifier(TASK_ID, main))
