#!/usr/bin/env python3
"""Deterministic verifier for task SpotHero--7 (generated by make_verifiers.py).

Ground truth is frozen from the reviewer's independent computation and live
honest walks on the review container (seed md5 482fb61d…). See
verify/README.md for the contract and task-specific caveats.
"""
import sys

from verify_lib import (Judge, check_package, check_seed_contract,
                        check_visited_path, check_visited_path_count,
                        check_answer_phrase,
                        check_answer_number, check_answer_any_number,
                        check_answer_any, check_only_tables_changed,
                        check_reservations_delta, check_any_new_reservation,
                        check_payment_methods_delta, check_profile_delta,
                        check_favorites_delta, check_new_user, final_answer,
                        run_verifier)

TASK_ID = "SpotHero--7"


def main(judge, traj, initial_db, after_db):
    answer = final_answer(traj)
    check_package(judge, traj, TASK_ID)
    check_seed_contract(judge, initial_db)
    check_visited_path(judge, traj, "search_results", r"/search\?.*search_string=Times")
    check_visited_path(judge, traj, "covered_filter", r"/search\?.*covered=1")
    check_visited_path(judge, traj, "price_sort", r"/search\?.*sort=price")
    check_visited_path(judge, traj, "fitting_garage_page", r"/facility/16130")
    check_visited_path(judge, traj, "checkout", r"/purchase/hourly\?facility=16130")
    check_visited_path(judge, traj, "confirmation", r"/purchase/confirmation/SH-")
    check_answer_phrase(judge, answer, "garage_named", '118 W 44th')
    check_answer_phrase(judge, answer, "height_fits_van", '7\' 1"')
    check_answer_number(judge, answer, "total", '36.29')
    check_reservations_delta(judge, initial_db, after_db, answer,
                             expect_added={'facility_id': 16130, 'kind': 'hourly', 'total': 36.29, 'email': 'van.driver@example.com', 'starts': '2026-10-03T19:00', 'ends': '2026-10-04T00:00', 'promo': '', 'user_id': None, 'status': 'upcoming'},
                             expect_updated=None)
    check_only_tables_changed(judge, initial_db, after_db, ('reservations',))
    return judge


if __name__ == "__main__":
    sys.exit(run_verifier(TASK_ID, main))
