#!/usr/bin/env python3
"""Deterministic verifier for task SpotHero--17 (generated by make_verifiers.py).

Ground truth is frozen from the reviewer's independent computation and live
honest walks on the review container (seed md5 482fb61d…). See
verify/README.md for the contract and task-specific caveats.
"""
import sys

from verify_lib import (Judge, check_package, check_seed_contract,
                        check_visited_path, check_visited_path_count,
                        check_answer_phrase,
                        check_answer_number, check_answer_any_number,
                        check_answer_any, check_only_tables_changed,
                        check_reservations_delta, check_any_new_reservation,
                        check_payment_methods_delta, check_profile_delta,
                        check_favorites_delta, check_new_user, final_answer,
                        run_verifier)

TASK_ID = "SpotHero--17"


def main(judge, traj, initial_db, after_db):
    answer = final_answer(traj)
    check_package(judge, traj, TASK_ID)
    check_seed_contract(judge, initial_db)
    check_visited_path(judge, traj, "signup", r"/auth/signup")
    check_visited_path(judge, traj, "account", r"/account$")
    check_visited_path(judge, traj, "united_center_search", r"/search\?.*search_string=United")
    check_visited_path(judge, traj, "price_sort", r"/search\?.*sort=price")
    check_visited_path(judge, traj, "cheapest_facility_page", r"/facility/100339")
    check_visited_path(judge, traj, "checkout", r"/purchase/hourly\?facility=100339")
    check_visited_path(judge, traj, "confirmation", r"/purchase/confirmation/SH-")
    check_answer_phrase(judge, answer, "account_created", 'Jordan Reyes')
    check_answer_phrase(judge, answer, "facility_named", '1850 - 1856 W Walnut')
    check_answer_number(judge, answer, "total", '11.49')
    uid = check_new_user(judge, initial_db, after_db,
                        email="jordan.reyes@example.com",
                        username="jordan_reyes", first_name="Jordan",
                        last_name="Reyes")
    check_reservations_delta(judge, initial_db, after_db, answer,
                             expect_added=dict(
                                 facility_id=100339, kind="hourly",
                                 total=11.49,
                                 email="jordan.reyes@example.com",
                                 starts="2026-10-03T17:00",
                                 ends="2026-10-03T23:00", promo="",
                                 user_id=uid, status="upcoming"),
                             expect_updated=None)
    check_only_tables_changed(judge, initial_db, after_db, ('users', 'reservations'))
    return judge


if __name__ == "__main__":
    sys.exit(run_verifier(TASK_ID, main))
