#!/usr/bin/env python3
"""Deterministic verifier for task SpotHero--8 (generated by make_verifiers.py).

Ground truth is frozen from the reviewer's independent computation and live
honest walks on the review container (seed md5 482fb61d…). See
verify/README.md for the contract and task-specific caveats.
"""
import sys

from verify_lib import (Judge, check_package, check_seed_contract,
                        check_visited_path, check_visited_path_count,
                        check_answer_phrase,
                        check_answer_number, check_answer_any_number,
                        check_answer_any, check_only_tables_changed,
                        check_reservations_delta, check_any_new_reservation,
                        check_payment_methods_delta, check_profile_delta,
                        check_favorites_delta, check_new_user, final_answer,
                        run_verifier)

TASK_ID = "SpotHero--8"


def main(judge, traj, initial_db, after_db):
    answer = final_answer(traj)
    check_package(judge, traj, TASK_ID)
    check_seed_contract(judge, initial_db)
    check_visited_path(judge, traj, "search_results", r"/search\?.*search_string=Millennium")
    check_visited_path(judge, traj, "first_facility_page", r"/facility/11603")
    check_visited_path(judge, traj, "second_facility_page", r"/facility/2175")
    check_visited_path(judge, traj, "checkout", r"/purchase/hourly\?facility=2175")
    check_visited_path(judge, traj, "confirmation", r"/purchase/confirmation/SH-")
    check_answer_number(judge, answer, "michigan_plaza_rating", '3.4')
    check_answer_number(judge, answer, "south_loop_rating", '4.8')
    check_answer_phrase(judge, answer, "booked_facility", 'South Loop Garage')
    check_answer_number(judge, answer, "total", '17.81')
    from comparison_checks import entity_numbers
    entity_numbers(judge, answer, "michigan_rating", [r"225 N(?:orth)? Michigan"], [r"318 S(?:outh)? Federal"], [3.4])
    entity_numbers(judge, answer, "federal_rating", [r"318 S(?:outh)? Federal"], [r"225 N(?:orth)? Michigan"], [4.8])
    check_reservations_delta(judge, initial_db, after_db, answer,
                             expect_added={'facility_id': 2175, 'kind': 'hourly', 'total': 17.81, 'email': 'jury.duty@example.com', 'starts': '2026-10-03T12:00', 'ends': '2026-10-03T18:00', 'promo': '', 'user_id': None, 'status': 'upcoming'},
                             expect_updated=None)
    check_only_tables_changed(judge, initial_db, after_db, ('reservations',))
    return judge


if __name__ == "__main__":
    sys.exit(run_verifier(TASK_ID, main))
