#!/usr/bin/env python3
"""Deterministic verifier for task SpotHero--20 (generated by make_verifiers.py).

Ground truth is frozen from the reviewer's independent computation and live
honest walks on the review container (seed md5 482fb61d…). See
verify/README.md for the contract and task-specific caveats.
"""
import sys

from verify_lib import (Judge, check_package, check_seed_contract,
                        check_visited_path, check_visited_path_count,
                        check_answer_phrase,
                        check_answer_number, check_answer_any_number,
                        check_answer_any, check_only_tables_changed,
                        check_reservations_delta, check_any_new_reservation,
                        check_payment_methods_delta, check_profile_delta,
                        check_favorites_delta, check_new_user, final_answer,
                        run_verifier)

TASK_ID = "SpotHero--20"


def main(judge, traj, initial_db, after_db):
    answer = final_answer(traj)
    check_package(judge, traj, TASK_ID)
    check_seed_contract(judge, initial_db)
    check_visited_path(judge, traj, "arena_destination", r"/destination/seattle/climate-pledge-arena-parking")
    check_visited_path(judge, traj, "kraken_event_search", r"/search\?kind=event&id=1391016")
    check_visited_path(judge, traj, "covered_inout_filters", r"/search\?kind=event&id=1391016.*covered=1.*in_out=1|/search\?kind=event&id=1391016.*in_out=1.*covered=1")
    check_visited_path(judge, traj, "cheapest_facility_page", r"/facility/22491")
    check_visited_path(judge, traj, "fees_toggle", r"/search\?kind=event&id=1391016.*fees=1")
    check_visited_path(judge, traj, "checkout", r"/purchase/hourly\?facility=22491")
    check_visited_path(judge, traj, "confirmation", r"/purchase/confirmation/SH-")
    check_answer_phrase(judge, answer, "parking_window_start", '4:00 PM')
    check_answer_phrase(judge, answer, "parking_window_end", '9:00 PM')
    check_answer_phrase(judge, answer, "garage_named", '465 Spring St')
    check_answer_phrase(judge, answer, "height_restriction", '6\' 6"')
    check_answer_phrase(judge, answer, "first_instruction", 'Enter this garage at 465 Spring St')
    check_answer_number(judge, answer, "total_with_fees", '13.11')
    check_reservations_delta(judge, initial_db, after_db, answer,
                             expect_added={'facility_id': 22491, 'kind': 'event', 'total': 13.11, 'email': 'kraken.fan@example.com', 'starts': '2026-10-04T16:00', 'ends': '2026-10-04T21:00', 'promo': '', 'user_id': None, 'status': 'upcoming'},
                             expect_updated=None)
    check_only_tables_changed(judge, initial_db, after_db, ('reservations',))
    return judge


if __name__ == "__main__":
    sys.exit(run_verifier(TASK_ID, main))
