#!/usr/bin/env python3
"""Deterministic verifier for task SpotHero--11 (generated by make_verifiers.py).

Ground truth is frozen from the reviewer's independent computation and live
honest walks on the review container (seed md5 482fb61d…). See
verify/README.md for the contract and task-specific caveats.
"""
import sys

from verify_lib import (Judge, check_package, check_seed_contract,
                        check_visited_path, check_visited_path_count,
                        check_answer_phrase,
                        check_answer_number, check_answer_any_number,
                        check_answer_any, check_only_tables_changed,
                        check_reservations_delta, check_any_new_reservation,
                        check_payment_methods_delta, check_profile_delta,
                        check_favorites_delta, check_new_user, final_answer,
                        run_verifier)

TASK_ID = "SpotHero--11"


def main(judge, traj, initial_db, after_db):
    answer = final_answer(traj)
    check_package(judge, traj, TASK_ID)
    check_seed_contract(judge, initial_db)
    check_visited_path(judge, traj, "wrigley_destination", r"/destination/chicago/wrigley-field-parking")
    check_visited_path(judge, traj, "destination_search", r"/search\?.*search_string=Wrigley|/search\?.*latitude=")
    check_visited_path(judge, traj, "featured_first_facility_page", r"/facility/129876")
    check_visited_path(judge, traj, "checkout", r"/purchase/hourly\?facility=129876")
    check_visited_path(judge, traj, "confirmation", r"/purchase/confirmation/SH-")
    check_answer_phrase(judge, answer, "featured_first", '1075 W Addison')
    check_answer_any(judge, answer, "suv_height_finding", ['no height restriction', 'no height restriction is listed'])
    check_answer_phrase(judge, answer, "first_instruction", 'Enter this location at 1075 W Addison St')
    check_answer_number(judge, answer, "total", '66.78')
    check_reservations_delta(judge, initial_db, after_db, answer,
                             expect_added={'facility_id': 129876, 'kind': 'hourly', 'total': 66.78, 'email': 'cubs.fan@example.com', 'starts': '2026-10-05T17:00', 'ends': '2026-10-05T23:00', 'promo': '', 'user_id': None, 'status': 'upcoming'},
                             expect_updated=None)
    check_only_tables_changed(judge, initial_db, after_db, ('reservations',))
    return judge


if __name__ == "__main__":
    sys.exit(run_verifier(TASK_ID, main))
