#!/usr/bin/env python3
"""Deterministic verifier for task SpotHero--18 (generated by make_verifiers.py).

Ground truth is frozen from the reviewer's independent computation and live
honest walks on the review container (seed md5 482fb61d…). See
verify/README.md for the contract and task-specific caveats.
"""
import sys

from verify_lib import (Judge, check_package, check_seed_contract,
                        check_visited_path, check_visited_path_count,
                        check_answer_phrase,
                        check_answer_number, check_answer_any_number,
                        check_answer_any, check_only_tables_changed,
                        check_reservations_delta, check_any_new_reservation,
                        check_payment_methods_delta, check_profile_delta,
                        check_favorites_delta, check_new_user, final_answer,
                        run_verifier)

TASK_ID = "SpotHero--18"


def main(judge, traj, initial_db, after_db):
    answer = final_answer(traj)
    check_package(judge, traj, TASK_ID)
    check_seed_contract(judge, initial_db)
    check_visited_path(judge, traj, "fenway_search", r"/search\?.*search_string=Fenway")
    check_visited_path(judge, traj, "covered_filter_fenway", r"/search\?.*covered=1.*search_string=Fenway|/search\?.*search_string=Fenway.*covered=1")
    check_visited_path(judge, traj, "times_square_search", r"/search\?.*search_string=Times")
    check_visited_path(judge, traj, "covered_filter_tsq", r"/search\?.*covered=1.*search_string=Times|/search\?.*search_string=Times.*covered=1")
    check_visited_path(judge, traj, "cheaper_facility_page", r"/facility/13153")
    check_visited_path(judge, traj, "checkout", r"/purchase/hourly\?facility=13153")
    check_visited_path(judge, traj, "confirmation", r"/purchase/confirmation/SH-")
    check_answer_phrase(judge, answer, "fenway_facility", '32 Fullerton')
    check_answer_number(judge, answer, "fenway_price", '21.20')
    check_answer_number(judge, answer, "tsq_price", '26.59')
    check_answer_phrase(judge, answer, "cheaper_city", 'Boston')
    check_answer_number(judge, answer, "price_difference", '5.39')
    check_answer_number(judge, answer, "booked_total", '22.47')
    check_reservations_delta(judge, initial_db, after_db, answer,
                             expect_added={'facility_id': 13153, 'kind': 'hourly', 'total': 22.47, 'email': 'city.hopper@example.com', 'starts': '2026-10-03T19:00', 'ends': '2026-10-04T00:00', 'promo': '', 'user_id': None, 'status': 'upcoming'},
                             expect_updated=None)
    check_only_tables_changed(judge, initial_db, after_db, ('reservations',))
    return judge


if __name__ == "__main__":
    sys.exit(run_verifier(TASK_ID, main))
