#!/usr/bin/env python3
"""Generate verify_<n>.py for the 20 super_lawyers tasks (deterministic
regeneration; do not edit the generated files by hand).

Ground truth below is HARDCODED from the reviewer's independent live walks
(runs/ under wh-super-lawyers-rereview-evidence, r2) and the frozen seed
contract in verify_lib.py. The r1 BLOCKED tasks (1 / 14 / 17) were re-anchored
by the c6b79316 fix (Criminal Defense Seattle / Chicago family law SERPs,
featured-lawyer city rendering); their verifiers now encode the re-anchored
task contracts. Stateful deltas re-frozen per the r2 walks: T6 additionally
records bob's inquiry to the Renton attorney; T7 creates two saved searches.
"""
from pathlib import Path

HEADER = '''#!/usr/bin/env python3
"""Verify {task_id}.

{doc}

Generated by make_verifiers.py (deterministic regeneration; do not edit by hand).
"""
from verify_lib import (check_answer_absent, check_answer_any, check_set_delta,
                        check_answer_count_at_least, check_answer_number,
                        check_answer_phrase, check_blocked, check_read_only,
                        check_rows_added, check_rows_changed, check_only_tables_changed,
                        check_rows_removed, check_screenshots,
                        check_trajectory_identity, check_visited_path,
                        final_answer, run_verifier)

TASK_ID = "{task_id}"


def run_checks(judge, traj, initial_db, after_db):
    answer = final_answer(traj)
    check_trajectory_identity(judge, traj, TASK_ID)
    check_screenshots(judge, traj)
{checks}


if __name__ == "__main__":
    raise SystemExit(run_verifier(TASK_ID, run_checks))
'''

LARA = "084fb116-f66d-4a57-affa-7e99e9c5f3f6"
SHERRI = "9abb5e11-4e2b-4b2f-9d97-cbed2cdfa327"
DUBIN = "11574067-209a-4624-af58-d7c9b2f4c1e9"
TRESI = "46018dc7-e5dd-4e80-8035-d10a4c156934"
NOW = "2026-09-26 12:00:00.000000"

SPECS = {}

SPECS[0] = dict(
    task_id="Super Lawyers--0",
    doc=("Seattle personal injury results -> the selectee first admitted in 2000 who "
         "handles aviation cases (Lara Herrmann) -> law school + Law Dragon honor -> "
         "log in as alice and send the rear-end-collision inquiry from the profile "
         "contact form."),
    checks=[
        'check_visited_path(judge, traj, "visited_pi_seattle_serp", r"/attorneys/personal-injury-plaintiff/washington/seattle/")',
        'check_visited_path(judge, traj, "visited_lara_profile", r"/profiles/washington/seattle/lawyer/lara-herrmann/084fb116")',
        'check_visited_path(judge, traj, "visited_login", r"/login")',
        'check_visited_path(judge, traj, "visited_contact_form", r"/profiles/contact/lawyer/084fb116")',
        'check_visited_path(judge, traj, "visited_inquiry_history", r"/account/inquiries")',
        'check_answer_phrase(judge, answer, "answer_attorney", "Lara Herrmann")',
        'check_answer_phrase(judge, answer, "answer_first_admitted", "2000")',
        'check_answer_phrase(judge, answer, "answer_law_school", "Seattle University School of Law")',
        'check_answer_any(judge, answer, "answer_law_dragon", ["Law Dragon", "Lawdragon", "top 500 consumer lawyers"])',
        'check_answer_phrase(judge, answer, "answer_aviation", "Aviation")',
        'check_only_tables_changed(judge, initial_db, after_db, {"inquiries"})',
        'check_rows_added(judge, initial_db, after_db, "inquiries", '
        f'[[None, 1, "{LARA}", None, None, None, None, None, None, "rx:(?i)rear", "{NOW}"]], '
        '"inquiry_sent_to_lara")',
    ])

SPECS[1] = dict(
    task_id="Super Lawyers--1",
    doc=("Attorney directory -> Criminal Defense category -> Seattle results page "
         "(re-anchored by the r2 fix; the DUI-DWI category offers no Seattle "
         "page) -> 27 rated attorneys, first card Chris Black (206-737-9807) -> "
         "his profile: University of Washington School of Law, first admitted "
         "2001 -> guest inquiry from the profile contact form "
         "(dui.help@example.com). Guest inquiries are NOT persisted, so the DB "
         "must stay read-only."),
    checks=[
        'check_visited_path(judge, traj, "visited_criminal_defense_category", r"/attorneys/criminal-defense/")',
        'check_visited_path(judge, traj, "visited_cd_seattle_serp", r"/attorneys/criminal-defense/washington/seattle/")',
        'check_visited_path(judge, traj, "visited_first_card_profile", r"/profiles/washington/seattle/lawyer/chris-black/34a81e85")',
        'check_visited_path(judge, traj, "visited_contact_form", r"/profiles/contact/lawyer/34a81e85")',
        'check_answer_number(judge, answer, "answer_rated_count", 27)',
        'check_answer_phrase(judge, answer, "answer_first_card", "Chris Black")',
        'check_answer_phrase(judge, answer, "answer_first_card_phone", "206-737-9807")',
        'check_answer_phrase(judge, answer, "answer_law_school", "University of Washington School of Law")',
        'check_answer_phrase(judge, answer, "answer_first_admitted", "2001")',
        'check_answer_any(judge, answer, "answer_inquiry_sent", ["inquiry has been sent", "inquiry was sent", "sent him a guest inquiry", "sent him an inquiry", "sent the inquiry", "sent an inquiry"])',
        'check_answer_phrase(judge, answer, "answer_guest_email", "dui.help@example.com")',
        'check_read_only(judge, initial_db, after_db)',
    ])

SPECS[2] = dict(
    task_id="Super Lawyers--2",
    doc=("Texas directory -> Dallas -> estate planning results -> the attorney first "
         "admitted in 1987 (Tresi Moore Weeks) -> name, law school, focus areas -> "
         "guest inquiry from the profile contact form (aunt.help@example.com). Guest "
         "inquiries are NOT persisted, so the DB must stay read-only."),
    checks=[
        'check_visited_path(judge, traj, "visited_dallas_estate_serp", r"/attorneys/estate-planning-and-probate/texas/dallas/")',
        'check_visited_path(judge, traj, "visited_tresi_profile", r"/profiles/texas/dallas/lawyer/tresi-moore-weeks/46018dc7")',
        'check_visited_path(judge, traj, "visited_contact_form", r"/profiles/contact/lawyer/46018dc7")',
        'check_answer_phrase(judge, answer, "answer_attorney", "Tresi Moore Weeks")',
        'check_answer_phrase(judge, answer, "answer_first_admitted", "1987")',
        'check_answer_phrase(judge, answer, "answer_law_school", "Baylor University School of Law")',
        'check_answer_count_at_least(judge, answer, "answer_focus_areas", '
        '["Living Wills", "Power of Attorney", "Probate & Estate Administration", '
        '"Probate and Estate Administration", "Trusts", "Wills"], 4)',
        'check_read_only(judge, initial_db, after_db)',
    ])

SPECS[3] = dict(
    task_id="Super Lawyers--3",
    doc=("Clifford Law Offices firm profile -> 6 attorneys + office address -> open "
         "EACH attorney's profile -> the partner first admitted in 1976 (Robert A. "
         "Clifford, National Law Journal Lifetime Achievement), the most recently "
         "admitted partner (Bradley M. Cosgrove, 2006), and how many attorneys were "
         "first admitted in the 1980s (2: Kevin P. Durkin 1980, Keith A. Hebeisen "
         "1983)."),
    checks=[
        'check_visited_path(judge, traj, "visited_lawyer_search", r"/attorneys/search/")',
        'check_visited_path(judge, traj, "visited_firm_profile", r"/lawfirm/clifford-law-offices/")',
        'check_visited_path(judge, traj, "visited_robert_profile", r"/profiles/illinois/chicago/lawyer/robert-a-clifford/")',
        'check_visited_path(judge, traj, "visited_durkin_profile", r"/lawyer/kevin-p-durkin/")',
        'check_visited_path(judge, traj, "visited_hebeisen_profile", r"/lawyer/keith-a-hebeisen/")',
        'check_visited_path(judge, traj, "visited_capra_profile", r"/lawyer/susan-a-capra/")',
        'check_visited_path(judge, traj, "visited_mcnulty_profile", r"/lawyer/shannon-m-mcnulty/")',
        'check_visited_path(judge, traj, "visited_cosgrove_profile", r"/lawyer/bradley-m-cosgrove/")',
        'check_answer_number(judge, answer, "answer_firm_attorney_count", 6)',
        'check_answer_phrase(judge, answer, "answer_office_address", "120 North LaSalle Street")',
        'check_answer_phrase(judge, answer, "answer_partner", "Robert A. Clifford")',
        'check_answer_phrase(judge, answer, "answer_first_admitted", "1976")',
        'check_answer_phrase(judge, answer, "answer_nlj_honor", "National Law Journal")',
        'check_answer_phrase(judge, answer, "answer_lifetime_honor", "Lifetime Achievement")',
        'check_answer_phrase(judge, answer, "answer_recent_partner", "Bradley M. Cosgrove")',
        'check_answer_phrase(judge, answer, "answer_recent_partner_year", "2006")',
        'check_answer_number(judge, answer, "answer_eighties_count", 2)',
        'check_answer_count_at_least(judge, answer, "answer_eighties_names", ["Kevin P. Durkin", "Keith A. Hebeisen"], 2)',
        'check_read_only(judge, initial_db, after_db)',
    ])

SPECS[4] = dict(
    task_id="Super Lawyers--4",
    doc=("2026 Washington Top 10 vs 2026 Women Washington Top 50 cross-comparison -> "
         "the four shared names -> the Top 10 selectee whose office city is Renton "
         "(Todd W. Gardner) -> his profile phone number."),
    checks=[
        'check_visited_path(judge, traj, "visited_wa_top_lists", r"/top-lists/washington/")',
        'check_visited_path(judge, traj, "visited_top_10", r"/top-lists/washington/top-10-2026-washington-super-lawyers/")',
        'check_visited_path(judge, traj, "visited_women_top_50", r"/top-lists/washington/top-50-2026-women-washington-super-lawyers/")',
        'check_visited_path(judge, traj, "visited_renton_profile", r"/lawyer/todd-w-gardner/")',
        'check_answer_count_at_least(judge, answer, "answer_shared_four", '
        '["Sherri M. Anderson", "Lora L. Brown", "Karolyn Hicks", "Lisa A. Sharpe"], 4)',
        'check_answer_phrase(judge, answer, "answer_renton_selectee", "Todd W. Gardner")',
        'check_answer_phrase(judge, answer, "answer_renton_city", "Renton")',
        'check_answer_phrase(judge, answer, "answer_phone", "425-226-7920")',
        'check_read_only(judge, initial_db, after_db)',
    ])

SPECS[5] = dict(
    task_id="Super Lawyers--5",
    doc=("Florida top lists -> 2 Top 100 lists, the women's list title, the first "
         "attorney on the Miami-specific Top 100 (Heather L. Apicella) -> her "
         "profile: Family Law, Boca Raton, phone 561-928-3963 -> the Florida-wide "
         "Top 100 (first Jeffrey A. Baskies) and the women's list (first Amy B. "
         "Beller); Heather appears on neither."),
    checks=[
        'check_visited_path(judge, traj, "visited_fl_top_lists", r"/top-lists/florida/")',
        'check_visited_path(judge, traj, "visited_miami_top_100", r"/top-lists/florida/top-100-2026-miami-super-lawyers/")',
        'check_visited_path(judge, traj, "visited_apicella_profile", r"/lawyer/heather-l-apicella/")',
        'check_visited_path(judge, traj, "visited_fl_top_100", r"/top-lists/florida/top-100-2026-florida-super-lawyers/")',
        'check_visited_path(judge, traj, "visited_women_top_50", r"/top-lists/florida/top-50-2026-women-florida-super-lawyers/")',
        'check_answer_number(judge, answer, "answer_top100_count", 2)',
        'check_answer_phrase(judge, answer, "answer_womens_title", "Top 50: 2026 Women Florida Super Lawyers")',
        'check_answer_phrase(judge, answer, "answer_first_miami", "Heather L. Apicella")',
        'check_answer_phrase(judge, answer, "answer_practice_area", "Family Law")',
        'check_answer_phrase(judge, answer, "answer_office_city", "Boca Raton")',
        'check_answer_phrase(judge, answer, "answer_phone", "561-928-3963")',
        'check_answer_phrase(judge, answer, "answer_first_fl_top_100", "Jeffrey A. Baskies")',
        'check_answer_phrase(judge, answer, "answer_first_women", "Amy B. Beller")',
        'check_answer_any(judge, answer, "answer_on_either_list", ["does not appear on either", "not on either", "appears on neither", "neither list"])',
        'check_read_only(judge, initial_db, after_db)',
    ])

SPECS[6] = dict(
    task_id="Super Lawyers--6",
    doc=("Log in as bob -> saved attorneys -> remove the two whose offices are in "
         "Tacoma (Thomas B. Vertetis) and Bellevue (Sherri M. Anderson) -> report "
         "the remaining count and kept names -> open the Renton attorney's (Todd "
         "W. Gardner's) profile, report his phone, and send him an inquiry about "
         "the rear-end collision case (logged-in: a new inquiry row for bob)."),
    checks=[
        'check_visited_path(judge, traj, "visited_login", r"/login")',
        'check_visited_path(judge, traj, "visited_favorites", r"/account/favorites")',
        'check_visited_path(judge, traj, "visited_gardner_profile", r"/lawyer/todd-w-gardner/")',
        'check_visited_path(judge, traj, "visited_contact_form", r"/profiles/contact/lawyer/9dfb2633")',
        'check_answer_number(judge, answer, "answer_remaining_count", 2)',
        'check_answer_count_at_least(judge, answer, "answer_kept", ["Todd W. Gardner", "Lora L. Brown"], 2)',
        'check_answer_phrase(judge, answer, "answer_removed_tacoma", "Thomas B. Vertetis")',
        'check_answer_phrase(judge, answer, "answer_removed_bellevue", "Sherri M. Anderson")',
        'check_answer_phrase(judge, answer, "answer_gardner_phone", "425-226-7920")',
        'check_answer_any(judge, answer, "answer_inquiry_sent", ["inquiry has been sent", "sent him an inquiry", "sent the inquiry", "sent an inquiry"])',
        'check_only_tables_changed(judge, initial_db, after_db, {"favorites", "inquiries"})',
        'check_rows_removed(judge, initial_db, after_db, "favorites", '
        f'[[None, 2, "{SHERRI}", None], [None, 2, "a7d4c917-69e1-4d19-acf6-386d53f1e258", None]], '
        '"bob_removed_tacoma_and_bellevue")',
        'check_rows_added(judge, initial_db, after_db, "favorites", [], '
        '"no_favorites_added")',
        'check_rows_added(judge, initial_db, after_db, "inquiries", '
        f'[[None, 2, "9dfb2633-21bc-44af-9cb7-4b5575069efe", None, None, None, None, None, None, "rx:(?i)rear|collision", "{NOW}"]], '
        '"bob_inquiry_to_gardner")',
    ])

SPECS[7] = dict(
    task_id="Super Lawyers--7",
    doc=("Log in as david -> create saved searches for personal injury attorneys in "
         "Miami AND family law attorneys in Chicago -> remove the DUI-DWI in "
         "Denver saved search -> report the remaining count (3) and the exact "
         "labels -> open the Miami personal injury results page and report how "
         "many attorney cards it lists (31)."),
    checks=[
        'check_visited_path(judge, traj, "visited_login", r"/login")',
        'check_visited_path(judge, traj, "visited_saved_searches", r"/account/saved-searches")',
        'check_visited_path(judge, traj, "visited_miami_pi_serp", r"/attorneys/personal-injury-plaintiff/florida/miami/")',
        'check_answer_number(judge, answer, "answer_remaining_count", 3)',
        'check_answer_phrase(judge, answer, "answer_new_label_miami", "Personal Injury in Miami, Florida")',
        'check_answer_phrase(judge, answer, "answer_new_label_chicago", "Family Law in Chicago, Illinois")',
        'check_answer_phrase(judge, answer, "answer_kept_label", "Employment & Labor in Boston")',
        'check_answer_number(judge, answer, "answer_miami_card_count", 31)',
        'check_only_tables_changed(judge, initial_db, after_db, {"saved_searches"})',
        'check_set_delta(judge, initial_db, after_db, "saved_searches", '
        '["user_id", "practice_slug", "city_slug", "state_slug", "label"], '
        '[[4, "dui-dwi", "denver", "colorado", "DUI-DWI in Denver"]], '
        '[[4, "personal-injury-plaintiff", "miami", "florida", '
        '"Personal Injury in Miami, Florida"], '
        '[4, "family-law", "chicago", "illinois", '
        '"Family Law in Chicago, Illinois"]], "david_saved_search_delta")',
    ])

SPECS[8] = dict(
    task_id="Super Lawyers--8",
    doc=("Log in as alice -> my inquiries -> the most recently contacted attorney "
         "(Matthew D. Dubin) and his practice city -> send him the follow-up "
         "settlement inquiry -> confirm it appears in the inquiry history."),
    checks=[
        'check_visited_path(judge, traj, "visited_login", r"/login")',
        'check_visited_path(judge, traj, "visited_inquiries", r"/account/inquiries")',
        'check_visited_path(judge, traj, "visited_dubin_profile", r"/lawyer/matthew-d-dubin/")',
        'check_visited_path(judge, traj, "visited_contact_form", r"/profiles/contact/lawyer/11574067")',
        'check_answer_any(judge, answer, "answer_recent_attorney", ["Matthew D. Dubin", "Matt Dubin"])',
        'check_answer_phrase(judge, answer, "answer_practice_city", "Seattle")',
        'check_answer_phrase(judge, answer, "answer_followup_topic", "settlement")',
        'check_only_tables_changed(judge, initial_db, after_db, {"inquiries"})',
        'check_rows_added(judge, initial_db, after_db, "inquiries", '
        f'[[None, 1, "{DUBIN}", None, None, None, None, None, None, "rx:(?i)settlement", "{NOW}"]], '
        '"alice_followup_to_dubin")',
    ])

SPECS[9] = dict(
    task_id="Super Lawyers--9",
    doc=("Log in as carol -> change display name to Carol D. Davis and email to "
         "carol.d.davis@example.com -> log out -> log back in with the new email -> "
         "confirm both changes -> report the saved-attorney count and each practice "
         "city."),
    checks=[
        'check_visited_path(judge, traj, "visited_login", r"/login")',
        'check_visited_path(judge, traj, "visited_profile_settings", r"/account/profile")',
        'check_visited_path(judge, traj, "visited_favorites", r"/account/favorites")',
        'check_answer_phrase(judge, answer, "answer_display_name", "Carol D. Davis")',
        'check_answer_phrase(judge, answer, "answer_new_email", "carol.d.davis@example.com")',
        'check_answer_number(judge, answer, "answer_saved_count", 3)',
        'check_answer_count_at_least(judge, answer, "answer_saved_cities", ["Seattle", "Bremerton"], 2)',
        'check_answer_count_at_least(judge, answer, "answer_saved_attorneys", '
        '["Steven W. Fogg", "Richard Friedman", "Karolyn Hicks"], 3)',
        'check_only_tables_changed(judge, initial_db, after_db, {"users"})',
        'check_rows_changed(judge, initial_db, after_db, "users", '
        '[[3, "carol.d.davis@example.com", "carol_d", "Carol D. Davis", '
        '"$2b$12$mTNQa9oqZyOoIJBpKN.0p.LVaApMSu9gZnYufEZrciM5QgBN7EM7u", None]], '
        '"carol_profile_edited")',
    ])

SPECS[10] = dict(
    task_id="Super Lawyers--10",
    doc=("Register maria_l / maria.lopez@example.com -> find Sherri M. Anderson via "
         "the 2026 Washington Top 10 list -> save her -> send the child-custody "
         "inquiry -> report the site's confirmation."),
    checks=[
        'check_visited_path(judge, traj, "visited_register", r"/register")',
        'check_visited_path(judge, traj, "visited_top_10", r"/top-lists/washington/top-10-2026-washington-super-lawyers/")',
        'check_visited_path(judge, traj, "visited_sherri_profile", r"/lawyer/sherri-m-anderson/")',
        'check_visited_path(judge, traj, "visited_contact_form", r"/profiles/contact/lawyer/9abb5e11")',
        'check_answer_phrase(judge, answer, "answer_attorney", "Sherri M. Anderson")',
        'check_answer_any(judge, answer, "answer_confirmation", '
        '["Your inquiry has been sent", "Track it under My inquiries"])',
        'check_only_tables_changed(judge, initial_db, after_db, {"users", "favorites", "inquiries"})',
        'check_rows_added(judge, initial_db, after_db, "users", '
        '[[None, "maria.lopez@example.com", "maria_l", None, "rx:\\\\$2b\\\\$12\\\\$", None]], '
        '"maria_registered")',
        'check_rows_added(judge, initial_db, after_db, "favorites", '
        f'[[None, 5, "{SHERRI}", None]], "maria_saved_sherri")',
        'check_rows_added(judge, initial_db, after_db, "inquiries", '
        f'[[None, 5, "{SHERRI}", None, None, None, None, None, None, "rx:(?i)custody", None]], '
        '"maria_inquiry_to_sherri")',
    ])

SPECS[11] = dict(
    task_id="Super Lawyers--11",
    doc=("Legal article resources -> the elderly financial abuse article -> two "
         "warning signs -> the Ask a Lawyer Florida elder-financial-abuse question "
         "-> answering attorney name, city, phone."),
    checks=[
        'check_visited_path(judge, traj, "visited_resources_hub", r"/resources/")',
        'check_visited_path(judge, traj, "visited_elder_abuse_article", r"/resources/elder-law/what-is-elderly-financial-abuse/")',
        'check_visited_path(judge, traj, "visited_answers_hub", r"/answers/")',
        'check_visited_path(judge, traj, "visited_fl_answer", r"/answers/elder-law/florida/")',
        'check_answer_count_at_least(judge, answer, "answer_warning_signs", '
        '["Large withdrawals", "changes in spending habits", '
        '"Someone the older person recently met", "undue influence", '
        '"Unpaid bills", "lottery", "telemarketing", "identity theft"], 2)',
        'check_answer_phrase(judge, answer, "answer_attorney", "Natasha Perez")',
        'check_answer_phrase(judge, answer, "answer_city", "Miami")',
        'check_answer_phrase(judge, answer, "answer_phone", "305-998-0051")',
        'check_read_only(judge, initial_db, after_db)',
    ])

SPECS[12] = dict(
    task_id="Super Lawyers--12",
    doc=("Ask a Lawyer search for severance questions -> the Minnesota question -> "
         "answering attorney Beth E. Bertelson (Minneapolis, MN), phone "
         "612-278-9832, one-sentence pre-signing recommendation, last answered "
         "April 8, 2026 -> search for overtime questions -> the New York one -> "
         "Joseph A. Fitapelli, last answered October 11, 2024 -> which was "
         "answered more recently (Minnesota)."),
    checks=[
        'check_visited_path(judge, traj, "visited_answers_hub", r"/answers/")',
        'check_visited_path(judge, traj, "visited_answers_search", r"/answers/search/")',
        'check_visited_path(judge, traj, "visited_mn_answer", r"/answers/employment-and-labor/minnesota/")',
        'check_visited_path(judge, traj, "visited_ny_answer", r"/answers/employment-and-labor/new-york/")',
        'check_answer_phrase(judge, answer, "answer_attorney", "Beth E. Bertelson")',
        'check_answer_phrase(judge, answer, "answer_city", "Minneapolis")',
        'check_answer_phrase(judge, answer, "answer_phone", "612-278-9832")',
        'check_answer_any(judge, answer, "answer_advice", '
        '["talk to an attorney before signing", "review the agreement", '
        '"attorney can help", "careful review"])',
        'check_answer_phrase(judge, answer, "answer_last_answered", "April 8, 2026")',
        'check_answer_phrase(judge, answer, "answer_ny_attorney", "Joseph A. Fitapelli")',
        'check_answer_phrase(judge, answer, "answer_ny_last_answered", "October 11, 2024")',
        'check_answer_any(judge, answer, "answer_more_recent", ["Minnesota question was answered more recently", "Minnesota severance question was answered more recently", "severance question was answered more recently", "Minnesota one was answered more recently"])',
        'check_read_only(judge, initial_db, after_db)',
    ])

SPECS[13] = dict(
    task_id="Super Lawyers--13",
    doc=("Ask a Lawyer hub -> browse answers by legal topic (criminal defense) -> the "
         "three states with criminal defense questions (Kansas, New Jersey, "
         "Pennsylvania) -> open EACH state's question: Kansas Paul D. Cramm "
         "(Overland Park, KS) + one piece of advice; New Jersey Peter G. Aziz "
         "(Clifton, NJ, phone 973-435-2245); Pennsylvania Evan Kelly (West "
         "Chester, PA, last answered September 28, 2022)."),
    checks=[
        'check_visited_path(judge, traj, "visited_answers_hub", r"/answers/")',
        'check_visited_path(judge, traj, "visited_criminal_defense_topic", r"/answers/criminal-defense/")',
        'check_visited_path(judge, traj, "visited_ks_answer", r"/answers/criminal-defense/kansas/")',
        'check_visited_path(judge, traj, "visited_nj_answer", r"/answers/criminal-defense/new-jersey/")',
        'check_visited_path(judge, traj, "visited_pa_answer", r"/answers/criminal-defense/pennsylvania/")',
        'check_answer_count_at_least(judge, answer, "answer_states", '
        '["Kansas", "New Jersey", "Pennsylvania"], 3)',
        'check_answer_phrase(judge, answer, "answer_ks_attorney", "Paul D. Cramm")',
        'check_answer_phrase(judge, answer, "answer_ks_city", "Overland Park")',
        'check_answer_any(judge, answer, "answer_ks_advice", '
        '["increases the penalties", "indecent liberties", "unable to give consent", '
        '"serious criminal offense"])',
        'check_answer_phrase(judge, answer, "answer_nj_attorney", "Peter G. Aziz")',
        'check_answer_phrase(judge, answer, "answer_nj_city", "Clifton")',
        'check_answer_phrase(judge, answer, "answer_nj_phone", "973-435-2245")',
        'check_answer_phrase(judge, answer, "answer_pa_attorney", "Evan Kelly")',
        'check_answer_phrase(judge, answer, "answer_pa_city", "West Chester")',
        'check_answer_phrase(judge, answer, "answer_pa_last_answered", "September 28, 2022")',
        'check_read_only(judge, initial_db, after_db)',
    ])

SPECS[14] = dict(
    task_id="Super Lawyers--14",
    doc=("April Jones feature article 'Finding the After' -> published in 2026 "
         "Colorado Super Lawyers magazine by Amy White on March 19, 2026 -> wish "
         "list (cat, condo, convertible) -> Sam Cary Bar Association twice -> 2027 "
         "Colorado Bar Association president -> Jones Law Firm -> featured lawyer "
         "April D. Jones with office city Greenwood Village, CO (rendered by the "
         "r2 fix) -> related article 'Bump in the Road': subtitle asks who's "
         "liable over a pothole, features Daniel Flanzig (re-anchored; the r1 "
         "BLOCKED office-city fact is now rendered on the article page)."),
    checks=[
        'check_visited_path(judge, traj, "visited_articles_hub", r"/articles/")',
        'check_visited_path(judge, traj, "visited_article", r"/articles/colorado/finding-the-after/")',
        'check_visited_path(judge, traj, "visited_related_article", r"/articles/online-features/bump-in-the-road/")',
        'check_answer_phrase(judge, answer, "answer_magazine", "Colorado Super Lawyers magazine")',
        'check_answer_phrase(judge, answer, "answer_author", "Amy White")',
        'check_answer_phrase(judge, answer, "answer_publication_date", "March 19, 2026")',
        'check_answer_count_at_least(judge, answer, "answer_wish_list", ["cat", "condo", "convertible"], 3)',
        'check_answer_phrase(judge, answer, "answer_bar_association", "Sam Cary Bar Association")',
        'check_answer_phrase(judge, answer, "answer_2027_role", "Colorado Bar Association")',
        'check_answer_phrase(judge, answer, "answer_firm", "Jones Law Firm")',
        'check_answer_phrase(judge, answer, "answer_featured_lawyer", "April D. Jones")',
        'check_answer_phrase(judge, answer, "answer_featured_city", "Greenwood Village, CO")',
        "check_answer_any(judge, answer, \"answer_related_subtitle\", [\"who's liable when you drive, bike or stumble over a pothole\", \"whos liable\", \"liable when you drive, bike or stumble over a pothole\", \"pothole\"])",
        'check_answer_any(judge, answer, "answer_related_attorney", ["Daniel Flanzig", "Christina R. Mercado", "Stephan Peskin"])',
        'check_read_only(judge, initial_db, after_db)',
    ])

SPECS[15] = dict(
    task_id="Super Lawyers--15",
    doc=("Houston immigration results -> compare the first five attorneys' languages "
         "by opening each profile -> the Italian speaker (Beatriz Trillos "
         "Ballerini), her law school, her exact selection years, and how many of "
         "the five speak Spanish."),
    checks=[
        'check_visited_path(judge, traj, "visited_houston_immigration_serp", r"/attorneys/immigration/texas/houston/")',
        'check_visited_path(judge, traj, "visited_beatriz_profile", r"/lawyer/beatriz-trillos-ballerini/")',
        'check_answer_any(judge, answer, "answer_italian_speaker", ["Beatriz Trillos Ballerini", "Beatriz Trillos-Ballerini", "Beatriz Trillos"])',
        'check_answer_phrase(judge, answer, "answer_law_school", "South Texas College of Law Houston")',
        'check_answer_any(judge, answer, "answer_selection_years", ["2021 - 2026", "2021-2026"])',
        'check_answer_any(judge, answer, "answer_spanish_count", ["three of the five", "3 of the five", "three of five", "3 of 5", "three speak spanish", "3 speak spanish", "three attorneys speak spanish"])',
        'check_answer_phrase(judge, answer, "answer_italian", "Italian")',
        'check_read_only(judge, initial_db, after_db)',
    ])

SPECS[16] = dict(
    task_id="Super Lawyers--16",
    doc=("Seattle criminal defense results -> the attorney whose practice-area chart "
         "shows 70 percent criminal defense while concentrating on DUI and "
         "white-collar work (Court Will) -> the three chart areas with exact "
         "percentages, first-admitted year, office phone."),
    checks=[
        'check_visited_path(judge, traj, "visited_cd_seattle_serp", r"/attorneys/criminal-defense/washington/seattle/")',
        'check_visited_path(judge, traj, "visited_court_will_profile", r"/lawyer/court-will/")',
        'check_answer_phrase(judge, answer, "answer_attorney", "Court Will")',
        'check_answer_phrase(judge, answer, "answer_chart_1", "70% Criminal Defense")',
        'check_answer_any(judge, answer, "answer_chart_2", ["20% Criminal Defense: DUI/DWI", "20% DUI/DWI"])',
        'check_answer_any(judge, answer, "answer_chart_3", ["10% Criminal Defense: White Collar", "10% White Collar"])',
        'check_answer_phrase(judge, answer, "answer_first_admitted", "2003")',
        'check_answer_phrase(judge, answer, "answer_phone", "206-209-5585")',
        'check_read_only(judge, initial_db, after_db)',
    ])

SPECS[17] = dict(
    task_id="Super Lawyers--17",
    doc=("Chicago family law attorneys results page (re-anchored by the r2 fix; the "
         "divorce x Chicago SERP was never captured) -> the three Cook County "
         "court locations with the First Municipal ((312) 603-6132) and Criminal "
         "Division ((773) 674-3160) phones -> 35 attorneys listed, first Mary Davis "
         "of Law Office of Mary Davis, P.C. (630-748-8819) -> her profile: DePaul "
         "University College of Law, first admitted 1991."),
    checks=[
        'check_visited_path(judge, traj, "visited_family_law_chicago_serp", r"/attorneys/family-law/illinois/chicago/")',
        'check_visited_path(judge, traj, "visited_mary_davis_profile", r"/lawyer/mary-e-davis/")',
        'check_answer_count_at_least(judge, answer, "answer_courts", '
        '["County Division", "Criminal Division", "First Municipal District", '
        '"Circuit Court of Cook County"], 3)',
        'check_answer_phrase(judge, answer, "answer_first_municipal_phone", "(312) 603-6132")',
        'check_answer_phrase(judge, answer, "answer_criminal_division_phone", "(773) 674-3160")',
        'check_answer_number(judge, answer, "answer_attorney_count", 35)',
        'check_answer_phrase(judge, answer, "answer_first_attorney", "Mary Davis")',
        'check_answer_phrase(judge, answer, "answer_first_attorney_firm", "Law Office of Mary Davis, P.C.")',
        'check_answer_phrase(judge, answer, "answer_first_attorney_phone", "630-748-8819")',
        'check_answer_phrase(judge, answer, "answer_law_school", "DePaul University College of Law")',
        'check_answer_phrase(judge, answer, "answer_first_admitted", "1991")',
        'check_read_only(judge, initial_db, after_db)',
    ])

SPECS[18] = dict(
    task_id="Super Lawyers--18",
    doc=("Denver DUI results -> page title, the nearby cities (Englewood, Greenwood "
         "Village, Castle Rock, Broomfield, Centennial), the related practice areas "
         "(Car Accident, Criminal Defense, Drug & Alcohol Violations, Trucking "
         "Accidents), and the first attorney card (Heidi Tripp, 983-224-0853) -> the "
         "related Car Accident page for Denver (no Denver attorneys listed) -> the "
         "DUI page for a nearby city (no attorneys listed there either)."),
    checks=[
        'check_visited_path(judge, traj, "visited_dui_denver_serp", r"/attorneys/dui-dwi/colorado/denver/")',
        'check_visited_path(judge, traj, "visited_car_accident_denver", r"/attorneys/motor-vehicle-accidents/colorado/denver/")',
        'check_visited_path(judge, traj, "visited_nearby_city_dui", r"/attorneys/dui-dwi/colorado/")',
        'check_answer_phrase(judge, answer, "answer_dui_page_title", "Top Rated DUI-DWI Lawyers in Denver")',
        'check_answer_count_at_least(judge, answer, "answer_nearby_cities", '
        '["Englewood", "Greenwood Village", "Castle Rock", "Broomfield", "Centennial"], 5)',
        'check_answer_count_at_least(judge, answer, "answer_related_areas", '
        '["Car Accident", "Criminal Defense", "Drug & Alcohol Violations", '
        '"Trucking Accidents"], 4)',
        'check_answer_phrase(judge, answer, "answer_first_card_name", "Heidi Tripp")',
        'check_answer_phrase(judge, answer, "answer_first_card_phone", "983-224-0853")',
        'check_answer_any(judge, answer, "answer_no_car_accident_attorneys", ["no Denver attorneys", "none are listed", "no attorneys", "0 attorney", "lists no"])',
        'check_answer_any(judge, answer, "answer_nearby_city_no_attorneys", ["no attorneys", "none are listed", "0 attorney", "lists no"])',
        'check_read_only(judge, initial_db, after_db)',
    ])

SPECS[19] = dict(
    task_id="Super Lawyers--19",
    doc=("Anne Bremner vs Kevin Coluccio -> open both profiles -> who has more total "
         "Super Lawyers selection years (Coluccio 28 vs Bremner 27), each "
         "first-admitted year (1983 / 1986), each law school (both Seattle "
         "University School of Law), each tagline practice area (Civil Litigation / "
         "Personal Injury), who appears first on the Seattle results page (Anne "
         "Bremner), and the phone of the one with more selection years "
         "(206-826-8200)."),
    checks=[
        'check_visited_path(judge, traj, "visited_pi_seattle_serp", r"/attorneys/personal-injury-plaintiff/washington/seattle/")',
        'check_visited_path(judge, traj, "visited_bremner_profile", r"/lawyer/anne-bremner/")',
        'check_visited_path(judge, traj, "visited_coluccio_profile", r"/lawyer/kevin-coluccio/")',
        'check_answer_phrase(judge, answer, "answer_more_years", "Kevin Coluccio")',
        'check_answer_phrase(judge, answer, "answer_coluccio_years", "28")',
        'check_answer_phrase(judge, answer, "answer_bremner_years", "27")',
        'check_answer_phrase(judge, answer, "answer_bremner_admitted", "1983")',
        'check_answer_phrase(judge, answer, "answer_coluccio_admitted", "1986")',
        'check_answer_phrase(judge, answer, "answer_bremner_law_school", "Seattle University School of Law")',
        'check_answer_phrase(judge, answer, "answer_coluccio_law_school", "Seattle University School of Law")',
        'check_answer_phrase(judge, answer, "answer_bremner_tagline", "Civil Litigation")',
        'check_answer_phrase(judge, answer, "answer_coluccio_tagline", "Personal Injury")',
        'check_answer_phrase(judge, answer, "answer_first_on_serp", "Anne Bremner")',
        'check_answer_phrase(judge, answer, "answer_phone", "206-826-8200")',
        'check_read_only(judge, initial_db, after_db)',
    ])


def main():
    out = Path(__file__).parent
    for n, spec in sorted(SPECS.items()):
        body = HEADER.format(task_id=spec["task_id"], doc=spec["doc"],
                             checks="\n".join(f"    {c}" for c in spec["checks"]))
        (out / f"verify_{n}.py").write_text(body)
        print(f"[gen] verify_{n}.py ({spec['task_id']})")


if __name__ == "__main__":
    main()
