#!/usr/bin/env python3
"""Verify Super Lawyers--10.

Register maria_l / maria.lopez@example.com -> find Sherri M. Anderson via the 2026 Washington Top 10 list -> save her -> send the child-custody inquiry -> report the site's confirmation.

Generated by make_verifiers.py (deterministic regeneration; do not edit by hand).
"""
from verify_lib import (check_answer_absent, check_answer_any, check_set_delta,
                        check_answer_count_at_least, check_answer_number,
                        check_answer_phrase, check_blocked, check_read_only,
                        check_rows_added, check_rows_changed, check_only_tables_changed,
                        check_rows_removed, check_screenshots,
                        check_trajectory_identity, check_visited_path,
                        final_answer, run_verifier)

TASK_ID = "Super Lawyers--10"


def run_checks(judge, traj, initial_db, after_db):
    answer = final_answer(traj)
    check_trajectory_identity(judge, traj, TASK_ID)
    check_screenshots(judge, traj)
    check_visited_path(judge, traj, "visited_register", r"/register")
    check_visited_path(judge, traj, "visited_top_10", r"/top-lists/washington/top-10-2026-washington-super-lawyers/")
    check_visited_path(judge, traj, "visited_sherri_profile", r"/lawyer/sherri-m-anderson/")
    check_visited_path(judge, traj, "visited_contact_form", r"/profiles/contact/lawyer/9abb5e11")
    check_answer_phrase(judge, answer, "answer_attorney", "Sherri M. Anderson")
    check_answer_any(judge, answer, "answer_confirmation", ["Your inquiry has been sent", "Track it under My inquiries"])
    check_only_tables_changed(judge, initial_db, after_db, {"users", "favorites", "inquiries"})
    check_rows_added(judge, initial_db, after_db, "users", [[None, "maria.lopez@example.com", "maria_l", None, "rx:\\$2b\\$12\\$", None]], "maria_registered")
    check_rows_added(judge, initial_db, after_db, "favorites", [[None, 5, "9abb5e11-4e2b-4b2f-9d97-cbed2cdfa327", None]], "maria_saved_sherri")
    check_rows_added(judge, initial_db, after_db, "inquiries", [[None, 5, "9abb5e11-4e2b-4b2f-9d97-cbed2cdfa327", None, None, None, None, None, None, "rx:(?i)custody", None]], "maria_inquiry_to_sherri")


if __name__ == "__main__":
    raise SystemExit(run_verifier(TASK_ID, run_checks))
