#!/usr/bin/env python3
"""Verify Super Lawyers--7.

Log in as david -> create saved searches for personal injury attorneys in Miami AND family law attorneys in Chicago -> remove the DUI-DWI in Denver saved search -> report the remaining count (3) and the exact labels -> open the Miami personal injury results page and report how many attorney cards it lists (31).

Generated by make_verifiers.py (deterministic regeneration; do not edit by hand).
"""
from verify_lib import (check_answer_absent, check_answer_any, check_set_delta,
                        check_answer_count_at_least, check_answer_number,
                        check_answer_phrase, check_blocked, check_read_only,
                        check_rows_added, check_rows_changed, check_only_tables_changed,
                        check_rows_removed, check_screenshots,
                        check_trajectory_identity, check_visited_path,
                        final_answer, run_verifier)

TASK_ID = "Super Lawyers--7"


def run_checks(judge, traj, initial_db, after_db):
    answer = final_answer(traj)
    check_trajectory_identity(judge, traj, TASK_ID)
    check_screenshots(judge, traj)
    check_visited_path(judge, traj, "visited_login", r"/login")
    check_visited_path(judge, traj, "visited_saved_searches", r"/account/saved-searches")
    check_visited_path(judge, traj, "visited_miami_pi_serp", r"/attorneys/personal-injury-plaintiff/florida/miami/")
    check_answer_number(judge, answer, "answer_remaining_count", 2)
    check_answer_phrase(judge, answer, "answer_new_label_miami", "Personal Injury in Miami, Florida")
    check_answer_phrase(judge, answer, "answer_kept_label", "Employment & Labor in Boston")
    check_answer_number(judge, answer, "answer_miami_card_count", 31)
    check_only_tables_changed(judge, initial_db, after_db, {"saved_searches"})
    check_set_delta(judge, initial_db, after_db, "saved_searches", ["user_id", "practice_slug", "city_slug", "state_slug", "label"], [[4, "dui-dwi", "denver", "colorado", "DUI-DWI in Denver"]], [[4, "personal-injury-plaintiff", "miami", "florida", "Personal Injury in Miami, Florida"]], "david_saved_search_delta")


if __name__ == "__main__":
    raise SystemExit(run_verifier(TASK_ID, run_checks))
