#!/usr/bin/env python3
"""Verify Super Lawyers--17.

Chicago family law attorneys results page (re-anchored by the r2 fix; the divorce x Chicago SERP was never captured) -> the three Cook County court locations with the First Municipal ((312) 603-6132) and Criminal Division ((773) 674-3160) phones -> 35 attorneys listed, first Mary Davis of Law Office of Mary Davis, P.C. (630-748-8819) -> her profile: DePaul University College of Law, first admitted 1991.

Generated by make_verifiers.py (deterministic regeneration; do not edit by hand).
"""
from verify_lib import (check_answer_absent, check_answer_any, check_set_delta,
                        check_answer_count_at_least, check_answer_number,
                        check_answer_phrase, check_blocked, check_read_only,
                        check_rows_added, check_rows_changed, check_only_tables_changed,
                        check_rows_removed, check_screenshots,
                        check_trajectory_identity, check_visited_path,
                        final_answer, run_verifier)

TASK_ID = "Super Lawyers--17"


def run_checks(judge, traj, initial_db, after_db):
    answer = final_answer(traj)
    check_trajectory_identity(judge, traj, TASK_ID)
    check_screenshots(judge, traj)
    check_visited_path(judge, traj, "visited_family_law_chicago_serp", r"/attorneys/family-law/illinois/chicago/")
    check_visited_path(judge, traj, "visited_mary_davis_profile", r"/lawyer/mary-e-davis/")
    check_answer_count_at_least(judge, answer, "answer_courts", ["County Division", "Criminal Division", "First Municipal District", "Circuit Court of Cook County"], 3)
    check_answer_phrase(judge, answer, "answer_first_municipal_phone", "(312) 603-6132")
    check_answer_phrase(judge, answer, "answer_criminal_division_phone", "(773) 674-3160")
    check_answer_number(judge, answer, "answer_attorney_count", 35)
    check_answer_phrase(judge, answer, "answer_first_attorney", "Mary Davis")
    check_answer_phrase(judge, answer, "answer_first_attorney_firm", "Law Office of Mary Davis, P.C.")
    check_answer_phrase(judge, answer, "answer_first_attorney_phone", "630-748-8819")
    check_answer_phrase(judge, answer, "answer_law_school", "DePaul University College of Law")
    check_answer_phrase(judge, answer, "answer_first_admitted", "1991")
    check_read_only(judge, initial_db, after_db)


if __name__ == "__main__":
    raise SystemExit(run_verifier(TASK_ID, run_checks))
