#!/usr/bin/env python3
"""Verify Super Lawyers--15.

Houston immigration results -> compare the first five attorneys' languages by opening each profile -> the Italian speaker (Beatriz Trillos Ballerini), her law school, her exact selection years, and how many of the five speak Spanish.

Generated by make_verifiers.py (deterministic regeneration; do not edit by hand).
"""
from verify_lib import (check_answer_absent, check_answer_any, check_set_delta,
                        check_answer_count_at_least, check_answer_number,
                        check_answer_phrase, check_blocked, check_read_only,
                        check_rows_added, check_rows_changed, check_only_tables_changed,
                        check_rows_removed, check_screenshots,
                        check_trajectory_identity, check_visited_path,
                        final_answer, run_verifier)

TASK_ID = "Super Lawyers--15"


def run_checks(judge, traj, initial_db, after_db):
    answer = final_answer(traj)
    check_trajectory_identity(judge, traj, TASK_ID)
    check_screenshots(judge, traj)
    check_visited_path(judge, traj, "visited_houston_immigration_serp", r"/attorneys/immigration/texas/houston/")
    check_visited_path(judge, traj, "visited_beatriz_profile", r"/lawyer/beatriz-trillos-ballerini/")
    check_answer_any(judge, answer, "answer_italian_speaker", ["Beatriz Trillos Ballerini", "Beatriz Trillos-Ballerini", "Beatriz Trillos"])
    check_answer_phrase(judge, answer, "answer_law_school", "South Texas College of Law Houston")
    check_answer_any(judge, answer, "answer_selection_years", ["2021 - 2026", "2021-2026"])
    check_answer_any(judge, answer, "answer_spanish_count", ["three of the five", "3 of the five", "three of five", "3 of 5", "three speak spanish", "3 speak spanish", "three attorneys speak spanish"])
    check_answer_phrase(judge, answer, "answer_italian", "Italian")
    check_read_only(judge, initial_db, after_db)


if __name__ == "__main__":
    raise SystemExit(run_verifier(TASK_ID, run_checks))
