#!/usr/bin/env python3
"""Verify Super Lawyers--19.

Anne Bremner vs Kevin Coluccio -> open both profiles -> who has more total Super Lawyers selection years (Coluccio 28 vs Bremner 27), each first-admitted year (1983 / 1986), each law school (both Seattle University School of Law), each tagline practice area (Civil Litigation / Personal Injury), who appears first on the Seattle results page (Anne Bremner), and the phone of the one with more selection years (206-826-8200).

Generated by make_verifiers.py (deterministic regeneration; do not edit by hand).
"""
from verify_lib import (check_answer_absent, check_answer_any, check_set_delta,
                        check_answer_count_at_least, check_answer_number,
                        check_answer_phrase, check_blocked, check_read_only,
                        check_rows_added, check_rows_changed, check_only_tables_changed,
                        check_rows_removed, check_screenshots,
                        check_trajectory_identity, check_visited_path,
                        final_answer, run_verifier)

TASK_ID = "Super Lawyers--19"


def run_checks(judge, traj, initial_db, after_db):
    answer = final_answer(traj)
    from reviewed_checks import check_answer
    check_answer(judge, traj, 19)
    check_trajectory_identity(judge, traj, TASK_ID)
    check_screenshots(judge, traj)
    check_visited_path(judge, traj, "visited_pi_seattle_serp", r"/attorneys/personal-injury-plaintiff/washington/seattle/")
    check_visited_path(judge, traj, "visited_bremner_profile", r"/lawyer/anne-bremner/")
    check_visited_path(judge, traj, "visited_coluccio_profile", r"/lawyer/kevin-coluccio/")
    check_answer_phrase(judge, answer, "answer_more_years", "Kevin Coluccio")
    check_answer_phrase(judge, answer, "answer_coluccio_years", "28")
    check_answer_phrase(judge, answer, "answer_bremner_years", "27")
    check_answer_phrase(judge, answer, "answer_bremner_admitted", "1983")
    check_answer_phrase(judge, answer, "answer_coluccio_admitted", "1986")
    check_answer_phrase(judge, answer, "answer_bremner_law_school", "Seattle University School of Law")
    check_answer_phrase(judge, answer, "answer_coluccio_law_school", "Seattle University School of Law")
    check_answer_phrase(judge, answer, "answer_bremner_tagline", "Civil Litigation")
    check_answer_phrase(judge, answer, "answer_coluccio_tagline", "Personal Injury")
    check_answer_phrase(judge, answer, "answer_first_on_serp", "Anne Bremner")
    check_answer_phrase(judge, answer, "answer_phone", "206-826-8200")
    check_read_only(judge, initial_db, after_db)


if __name__ == "__main__":
    raise SystemExit(run_verifier(TASK_ID, run_checks))
