#!/usr/bin/env python3
"""Verify Super Lawyers--0.

Seattle personal injury results -> the selectee first admitted in 2000 who handles aviation cases (Lara Herrmann) -> law school + Law Dragon honor -> log in as alice and send the rear-end-collision inquiry from the profile contact form.

Generated by make_verifiers.py (deterministic regeneration; do not edit by hand).
"""
from verify_lib import (check_answer_absent, check_answer_any, check_set_delta,
                        check_answer_count_at_least, check_answer_number,
                        check_answer_phrase, check_blocked, check_read_only,
                        check_rows_added, check_rows_changed, check_only_tables_changed,
                        check_rows_removed, check_screenshots,
                        check_trajectory_identity, check_visited_path,
                        final_answer, run_verifier)

TASK_ID = "Super Lawyers--0"


def run_checks(judge, traj, initial_db, after_db):
    answer = final_answer(traj)
    check_trajectory_identity(judge, traj, TASK_ID)
    check_screenshots(judge, traj)
    check_visited_path(judge, traj, "visited_pi_seattle_serp", r"/attorneys/personal-injury-plaintiff/washington/seattle/")
    check_visited_path(judge, traj, "visited_lara_profile", r"/profiles/washington/seattle/lawyer/lara-herrmann/084fb116")
    check_visited_path(judge, traj, "visited_login", r"/login")
    check_visited_path(judge, traj, "visited_contact_form", r"/profiles/contact/lawyer/084fb116")
    check_visited_path(judge, traj, "visited_inquiry_history", r"/account/inquiries")
    check_answer_phrase(judge, answer, "answer_attorney", "Lara Herrmann")
    check_answer_phrase(judge, answer, "answer_first_admitted", "2000")
    check_answer_phrase(judge, answer, "answer_law_school", "Seattle University School of Law")
    check_answer_any(judge, answer, "answer_law_dragon", ["Law Dragon", "Lawdragon", "top 500 consumer lawyers"])
    check_answer_phrase(judge, answer, "answer_aviation", "Aviation")
    check_only_tables_changed(judge, initial_db, after_db, {"inquiries"})
    check_rows_added(judge, initial_db, after_db, "inquiries", [[None, 1, "084fb116-f66d-4a57-affa-7e99e9c5f3f6", None, None, None, None, None, None, "rx:(?i)rear", "2026-09-26 12:00:00.000000"]], "inquiry_sent_to_lara")


if __name__ == "__main__":
    raise SystemExit(run_verifier(TASK_ID, run_checks))
