#!/usr/bin/env python3
"""Verify Super Lawyers--9.

Log in as carol -> change display name to Carol D. Davis and email to carol.d.davis@example.com -> log out -> log back in with the new email -> confirm both changes -> report the saved-attorney count and each practice city.

Generated by make_verifiers.py (deterministic regeneration; do not edit by hand).
"""
from verify_lib import (check_answer_absent, check_answer_any, check_set_delta,
                        check_answer_count_at_least, check_answer_number,
                        check_answer_phrase, check_blocked, check_read_only,
                        check_rows_added, check_rows_changed, check_only_tables_changed,
                        check_rows_removed, check_screenshots,
                        check_trajectory_identity, check_visited_path,
                        final_answer, run_verifier)

TASK_ID = "Super Lawyers--9"


def run_checks(judge, traj, initial_db, after_db):
    answer = final_answer(traj)
    check_trajectory_identity(judge, traj, TASK_ID)
    check_screenshots(judge, traj)
    check_visited_path(judge, traj, "visited_login", r"/login")
    check_visited_path(judge, traj, "visited_profile_settings", r"/account/profile")
    check_answer_phrase(judge, answer, "answer_display_name", "Carol D. Davis")
    check_answer_phrase(judge, answer, "answer_new_email", "carol.d.davis@example.com")
    check_only_tables_changed(judge, initial_db, after_db, {"users"})
    check_rows_changed(judge, initial_db, after_db, "users", [[3, "carol.d.davis@example.com", "carol_d", "Carol D. Davis", "$2b$12$mTNQa9oqZyOoIJBpKN.0p.LVaApMSu9gZnYufEZrciM5QgBN7EM7u", None]], "carol_profile_edited")


if __name__ == "__main__":
    raise SystemExit(run_verifier(TASK_ID, run_checks))
