#!/usr/bin/env python3
"""Verify Super Lawyers--18.

Denver DUI results -> page title, the nearby cities (Englewood, Greenwood Village, Castle Rock, Broomfield, Centennial), the related practice areas (Car Accident, Criminal Defense, Drug & Alcohol Violations, Trucking Accidents), and the first attorney card (Heidi Tripp, 983-224-0853) -> the related Car Accident page for Denver (no Denver attorneys listed) -> the DUI page for a nearby city (no attorneys listed there either).

Generated by make_verifiers.py (deterministic regeneration; do not edit by hand).
"""
from verify_lib import (check_answer_absent, check_answer_any, check_set_delta,
                        check_answer_count_at_least, check_answer_number,
                        check_answer_phrase, check_blocked, check_read_only,
                        check_rows_added, check_rows_changed, check_only_tables_changed,
                        check_rows_removed, check_screenshots,
                        check_trajectory_identity, check_visited_path,
                        final_answer, run_verifier)

TASK_ID = "Super Lawyers--18"


def run_checks(judge, traj, initial_db, after_db):
    answer = final_answer(traj)
    check_trajectory_identity(judge, traj, TASK_ID)
    check_screenshots(judge, traj)
    check_visited_path(judge, traj, "visited_dui_denver_serp", r"/attorneys/dui-dwi/colorado/denver/")
    check_visited_path(judge, traj, "visited_car_accident_denver", r"/attorneys/motor-vehicle-accidents/colorado/denver/")
    check_visited_path(judge, traj, "visited_nearby_city_dui", r"/attorneys/dui-dwi/colorado/")
    check_answer_phrase(judge, answer, "answer_dui_page_title", "Top Rated DUI-DWI Lawyers in Denver")
    check_answer_count_at_least(judge, answer, "answer_nearby_cities", ["Englewood", "Greenwood Village", "Castle Rock", "Broomfield", "Centennial"], 5)
    check_answer_count_at_least(judge, answer, "answer_related_areas", ["Car Accident", "Criminal Defense", "Drug & Alcohol Violations", "Trucking Accidents"], 4)
    check_answer_phrase(judge, answer, "answer_first_card_name", "Heidi Tripp")
    check_answer_phrase(judge, answer, "answer_first_card_phone", "983-224-0853")
    check_answer_any(judge, answer, "answer_no_car_accident_attorneys", ["no Denver attorneys", "none are listed", "no attorneys", "0 attorney", "lists no"])
    check_answer_any(judge, answer, "answer_nearby_city_no_attorneys", ["no attorneys", "none are listed", "0 attorney", "lists no"])
    check_read_only(judge, initial_db, after_db)


if __name__ == "__main__":
    raise SystemExit(run_verifier(TASK_ID, run_checks))
