#!/usr/bin/env python3
"""Verify Super Lawyers--4.

2026 Washington Top 10 vs 2026 Women Washington Top 50 cross-comparison -> the four shared names -> the Top 10 selectee whose office city is Renton (Todd W. Gardner) -> his profile phone number.

Generated by make_verifiers.py (deterministic regeneration; do not edit by hand).
"""
from verify_lib import (check_answer_absent, check_answer_any, check_set_delta,
                        check_answer_count_at_least, check_answer_number,
                        check_answer_phrase, check_blocked, check_read_only,
                        check_rows_added, check_rows_changed, check_only_tables_changed,
                        check_rows_removed, check_screenshots,
                        check_trajectory_identity, check_visited_path,
                        final_answer, run_verifier)

TASK_ID = "Super Lawyers--4"


def run_checks(judge, traj, initial_db, after_db):
    answer = final_answer(traj)
    check_trajectory_identity(judge, traj, TASK_ID)
    check_screenshots(judge, traj)
    check_visited_path(judge, traj, "visited_wa_top_lists", r"/top-lists/washington/")
    check_visited_path(judge, traj, "visited_top_10", r"/top-lists/washington/top-10-2026-washington-super-lawyers/")
    check_visited_path(judge, traj, "visited_women_top_50", r"/top-lists/washington/top-50-2026-women-washington-super-lawyers/")
    check_visited_path(judge, traj, "visited_renton_profile", r"/lawyer/todd-w-gardner/")
    check_answer_count_at_least(judge, answer, "answer_shared_four", ["Sherri M. Anderson", "Lora L. Brown", "Karolyn Hicks", "Lisa A. Sharpe"], 4)
    check_answer_phrase(judge, answer, "answer_renton_selectee", "Todd W. Gardner")
    check_answer_phrase(judge, answer, "answer_renton_city", "Renton")
    check_answer_phrase(judge, answer, "answer_phone", "425-226-7920")
    check_read_only(judge, initial_db, after_db)


if __name__ == "__main__":
    raise SystemExit(run_verifier(TASK_ID, run_checks))
