#!/usr/bin/env python3
"""Verify Super Lawyers--1.

Attorney directory -> Criminal Defense category -> Seattle results page (re-anchored by the r2 fix; the DUI-DWI category offers no Seattle page) -> 27 rated attorneys, first card Chris Black (206-737-9807) -> his profile: University of Washington School of Law, first admitted 2001 -> guest inquiry from the profile contact form (dui.help@example.com). Guest inquiries are NOT persisted, so the DB must stay read-only.

Generated by make_verifiers.py (deterministic regeneration; do not edit by hand).
"""
from verify_lib import (check_answer_absent, check_answer_any, check_set_delta,
                        check_answer_count_at_least, check_answer_number,
                        check_answer_phrase, check_blocked, check_read_only,
                        check_rows_added, check_rows_changed, check_only_tables_changed,
                        check_rows_removed, check_screenshots,
                        check_trajectory_identity, check_visited_path,
                        final_answer, run_verifier)

TASK_ID = "Super Lawyers--1"


def run_checks(judge, traj, initial_db, after_db):
    answer = final_answer(traj)
    check_trajectory_identity(judge, traj, TASK_ID)
    check_screenshots(judge, traj)
    check_visited_path(judge, traj, "visited_criminal_defense_category", r"/attorneys/criminal-defense/")
    check_visited_path(judge, traj, "visited_cd_seattle_serp", r"/attorneys/criminal-defense/washington/seattle/")
    check_visited_path(judge, traj, "visited_first_card_profile", r"/profiles/washington/seattle/lawyer/chris-black/34a81e85")
    check_visited_path(judge, traj, "visited_contact_form", r"/profiles/contact/lawyer/34a81e85")
    check_answer_number(judge, answer, "answer_rated_count", 27)
    check_answer_phrase(judge, answer, "answer_first_card", "Chris Black")
    check_answer_phrase(judge, answer, "answer_first_card_phone", "206-737-9807")
    check_answer_phrase(judge, answer, "answer_law_school", "University of Washington School of Law")
    check_answer_phrase(judge, answer, "answer_first_admitted", "2001")
    check_answer_any(judge, answer, "answer_inquiry_sent", ["inquiry has been sent", "inquiry was sent", "sent him a guest inquiry", "sent him an inquiry", "sent the inquiry", "sent an inquiry"])
    check_answer_phrase(judge, answer, "answer_guest_email", "dui.help@example.com")
    check_read_only(judge, initial_db, after_db)


if __name__ == "__main__":
    raise SystemExit(run_verifier(TASK_ID, run_checks))
