#!/usr/bin/env python3
"""Verify Super Lawyers--13.

Ask a Lawyer hub -> browse answers by legal topic (criminal defense) -> the three states with criminal defense questions (Kansas, New Jersey, Pennsylvania) -> open EACH state's question: Kansas Paul D. Cramm (Overland Park, KS) + one piece of advice; New Jersey Peter G. Aziz (Clifton, NJ, phone 973-435-2245); Pennsylvania Evan Kelly (West Chester, PA, last answered September 28, 2022).

Generated by make_verifiers.py (deterministic regeneration; do not edit by hand).
"""
from verify_lib import (check_answer_absent, check_answer_any, check_set_delta,
                        check_answer_count_at_least, check_answer_number,
                        check_answer_phrase, check_blocked, check_read_only,
                        check_rows_added, check_rows_changed, check_only_tables_changed,
                        check_rows_removed, check_screenshots,
                        check_trajectory_identity, check_visited_path,
                        final_answer, run_verifier)

TASK_ID = "Super Lawyers--13"


def run_checks(judge, traj, initial_db, after_db):
    answer = final_answer(traj)
    check_trajectory_identity(judge, traj, TASK_ID)
    check_screenshots(judge, traj)
    check_visited_path(judge, traj, "visited_answers_hub", r"/answers/")
    check_visited_path(judge, traj, "visited_criminal_defense_topic", r"/answers/criminal-defense/")
    check_visited_path(judge, traj, "visited_ks_answer", r"/answers/criminal-defense/kansas/")
    check_visited_path(judge, traj, "visited_nj_answer", r"/answers/criminal-defense/new-jersey/")
    check_visited_path(judge, traj, "visited_pa_answer", r"/answers/criminal-defense/pennsylvania/")
    check_answer_count_at_least(judge, answer, "answer_states", ["Kansas", "New Jersey", "Pennsylvania"], 3)
    check_answer_phrase(judge, answer, "answer_ks_attorney", "Paul D. Cramm")
    check_answer_phrase(judge, answer, "answer_ks_city", "Overland Park")
    check_answer_any(judge, answer, "answer_ks_advice", ["increases the penalties", "indecent liberties", "unable to give consent", "serious criminal offense"])
    check_answer_phrase(judge, answer, "answer_nj_attorney", "Peter G. Aziz")
    check_answer_phrase(judge, answer, "answer_nj_city", "Clifton")
    check_answer_phrase(judge, answer, "answer_nj_phone", "973-435-2245")
    check_answer_phrase(judge, answer, "answer_pa_attorney", "Evan Kelly")
    check_answer_phrase(judge, answer, "answer_pa_city", "West Chester")
    check_answer_phrase(judge, answer, "answer_pa_last_answered", "September 28, 2022")
    check_read_only(judge, initial_db, after_db)


if __name__ == "__main__":
    raise SystemExit(run_verifier(TASK_ID, run_checks))
