#!/usr/bin/env python3
"""Verify Super Lawyers--6.

Log in as bob -> saved attorneys -> remove the two whose offices are in Tacoma (Thomas B. Vertetis) and Bellevue (Sherri M. Anderson) -> report the remaining count and kept names -> open the Renton attorney's (Todd W. Gardner's) profile, report his phone, and send him an inquiry about the rear-end collision case (logged-in: a new inquiry row for bob).

Generated by make_verifiers.py (deterministic regeneration; do not edit by hand).
"""
from verify_lib import (check_answer_absent, check_answer_any, check_set_delta,
                        check_answer_count_at_least, check_answer_number,
                        check_answer_phrase, check_blocked, check_read_only,
                        check_rows_added, check_rows_changed, check_only_tables_changed,
                        check_rows_removed, check_screenshots,
                        check_trajectory_identity, check_visited_path,
                        final_answer, run_verifier)

TASK_ID = "Super Lawyers--6"


def run_checks(judge, traj, initial_db, after_db):
    answer = final_answer(traj)
    check_trajectory_identity(judge, traj, TASK_ID)
    check_screenshots(judge, traj)
    check_visited_path(judge, traj, "visited_login", r"/login")
    check_visited_path(judge, traj, "visited_favorites", r"/account/favorites")
    check_visited_path(judge, traj, "visited_gardner_profile", r"/lawyer/todd-w-gardner/")
    check_visited_path(judge, traj, "visited_contact_form", r"/profiles/contact/lawyer/9dfb2633")
    check_answer_number(judge, answer, "answer_remaining_count", 2)
    check_answer_count_at_least(judge, answer, "answer_kept", ["Todd W. Gardner", "Lora L. Brown"], 2)
    check_answer_phrase(judge, answer, "answer_removed_tacoma", "Thomas B. Vertetis")
    check_answer_phrase(judge, answer, "answer_removed_bellevue", "Sherri M. Anderson")
    check_answer_phrase(judge, answer, "answer_gardner_phone", "425-226-7920")
    check_answer_any(judge, answer, "answer_inquiry_sent", ["inquiry has been sent", "sent him an inquiry", "sent the inquiry", "sent an inquiry"])
    check_only_tables_changed(judge, initial_db, after_db, {"favorites", "inquiries"})
    check_rows_removed(judge, initial_db, after_db, "favorites", [[None, 2, "9abb5e11-4e2b-4b2f-9d97-cbed2cdfa327", None], [None, 2, "a7d4c917-69e1-4d19-acf6-386d53f1e258", None]], "bob_removed_tacoma_and_bellevue")
    check_rows_added(judge, initial_db, after_db, "favorites", [], "no_favorites_added")
    check_rows_added(judge, initial_db, after_db, "inquiries", [[None, 2, "9dfb2633-21bc-44af-9cb7-4b5575069efe", None, None, None, None, None, None, "rx:(?i)rear|collision", "2026-09-26 12:00:00.000000"]], "bob_inquiry_to_gardner")


if __name__ == "__main__":
    raise SystemExit(run_verifier(TASK_ID, run_checks))
