#!/usr/bin/env python3
"""Verify Super Lawyers--8.

Log in as alice -> my inquiries -> the most recently contacted attorney (Matthew D. Dubin) and his practice city -> send him the follow-up settlement inquiry -> confirm it appears in the inquiry history.

Generated by make_verifiers.py (deterministic regeneration; do not edit by hand).
"""
from verify_lib import (check_answer_absent, check_answer_any, check_set_delta,
                        check_answer_count_at_least, check_answer_number,
                        check_answer_phrase, check_blocked, check_read_only,
                        check_rows_added, check_rows_changed, check_only_tables_changed,
                        check_rows_removed, check_screenshots,
                        check_trajectory_identity, check_visited_path,
                        final_answer, run_verifier)

TASK_ID = "Super Lawyers--8"


def run_checks(judge, traj, initial_db, after_db):
    answer = final_answer(traj)
    check_trajectory_identity(judge, traj, TASK_ID)
    check_screenshots(judge, traj)
    check_visited_path(judge, traj, "visited_login", r"/login")
    check_visited_path(judge, traj, "visited_inquiries", r"/account/inquiries")
    check_visited_path(judge, traj, "visited_dubin_profile", r"/lawyer/matthew-d-dubin/")
    check_visited_path(judge, traj, "visited_contact_form", r"/profiles/contact/lawyer/11574067")
    check_answer_any(judge, answer, "answer_recent_attorney", ["Matthew D. Dubin", "Matt Dubin"])
    check_answer_phrase(judge, answer, "answer_practice_city", "Seattle")
    check_answer_phrase(judge, answer, "answer_followup_topic", "settlement")
    check_only_tables_changed(judge, initial_db, after_db, {"inquiries"})
    check_rows_added(judge, initial_db, after_db, "inquiries", [[None, 1, "11574067-209a-4624-af58-d7c9b2f4c1e9", None, None, None, None, None, None, "rx:(?i)settlement", "2026-09-26 12:00:00.000000"]], "alice_followup_to_dubin")


if __name__ == "__main__":
    raise SystemExit(run_verifier(TASK_ID, run_checks))
