#!/usr/bin/env python3
"""Verify Super Lawyers--12.

Ask a Lawyer search for severance questions -> the Minnesota question -> answering attorney Beth E. Bertelson (Minneapolis, MN), phone 612-278-9832, one-sentence pre-signing recommendation, last answered April 8, 2026 -> search for overtime questions -> the New York one -> Joseph A. Fitapelli, last answered October 11, 2024 -> which was answered more recently (Minnesota).

Generated by make_verifiers.py (deterministic regeneration; do not edit by hand).
"""
from verify_lib import (check_answer_absent, check_answer_any, check_set_delta,
                        check_answer_count_at_least, check_answer_number,
                        check_answer_phrase, check_blocked, check_read_only,
                        check_rows_added, check_rows_changed, check_only_tables_changed,
                        check_rows_removed, check_screenshots,
                        check_trajectory_identity, check_visited_path,
                        final_answer, run_verifier)

TASK_ID = "Super Lawyers--12"


def run_checks(judge, traj, initial_db, after_db):
    answer = final_answer(traj)
    from reviewed_checks import check_answer
    check_answer(judge, traj, 12)
    check_trajectory_identity(judge, traj, TASK_ID)
    check_screenshots(judge, traj)
    check_visited_path(judge, traj, "visited_answers_hub", r"/answers/")
    check_visited_path(judge, traj, "visited_answers_search", r"/answers/search/")
    check_visited_path(judge, traj, "visited_mn_answer", r"/answers/employment-and-labor/minnesota/")
    check_visited_path(judge, traj, "visited_ny_answer", r"/answers/employment-and-labor/new-york/")
    check_answer_phrase(judge, answer, "answer_attorney", "Beth E. Bertelson")
    check_answer_phrase(judge, answer, "answer_city", "Minneapolis")
    check_answer_phrase(judge, answer, "answer_phone", "612-278-9832")
    check_answer_any(judge, answer, "answer_advice", ["talk to an attorney before signing", "review the agreement", "attorney can help", "careful review"])
    check_answer_phrase(judge, answer, "answer_last_answered", "April 8, 2026")
    check_answer_phrase(judge, answer, "answer_ny_attorney", "Joseph A. Fitapelli")
    check_answer_phrase(judge, answer, "answer_ny_last_answered", "October 11, 2024")
    check_read_only(judge, initial_db, after_db)


if __name__ == "__main__":
    raise SystemExit(run_verifier(TASK_ID, run_checks))
