#!/usr/bin/env python3
"""Verify Super Lawyers--2.

Texas directory -> Dallas -> estate planning results -> the attorney first admitted in 1987 (Tresi Moore Weeks) -> name, law school, focus areas -> guest inquiry from the profile contact form (aunt.help@example.com). Guest inquiries are NOT persisted, so the DB must stay read-only.

Generated by make_verifiers.py (deterministic regeneration; do not edit by hand).
"""
from verify_lib import (check_answer_absent, check_answer_any, check_set_delta,
                        check_answer_count_at_least, check_answer_number,
                        check_answer_phrase, check_blocked, check_read_only,
                        check_rows_added, check_rows_changed, check_only_tables_changed,
                        check_rows_removed, check_screenshots,
                        check_trajectory_identity, check_visited_path,
                        final_answer, run_verifier)

TASK_ID = "Super Lawyers--2"


def run_checks(judge, traj, initial_db, after_db):
    answer = final_answer(traj)
    check_trajectory_identity(judge, traj, TASK_ID)
    check_screenshots(judge, traj)
    check_visited_path(judge, traj, "visited_dallas_estate_serp", r"/attorneys/estate-planning-and-probate/texas/dallas/")
    check_visited_path(judge, traj, "visited_tresi_profile", r"/profiles/texas/dallas/lawyer/tresi-moore-weeks/46018dc7")
    check_visited_path(judge, traj, "visited_contact_form", r"/profiles/contact/lawyer/46018dc7")
    check_answer_phrase(judge, answer, "answer_attorney", "Tresi Moore Weeks")
    check_answer_phrase(judge, answer, "answer_first_admitted", "1987")
    check_answer_phrase(judge, answer, "answer_law_school", "Baylor University School of Law")
    check_answer_count_at_least(judge, answer, "answer_focus_areas", ["Living Wills", "Power of Attorney", "Probate & Estate Administration", "Probate and Estate Administration", "Trusts", "Wills"], 4)
    check_read_only(judge, initial_db, after_db)


if __name__ == "__main__":
    raise SystemExit(run_verifier(TASK_ID, run_checks))
