#!/usr/bin/env python3
"""Verify Super Lawyers--5.

Florida top lists -> 2 Top 100 lists, the women's list title, the first attorney on the Miami-specific Top 100 (Heather L. Apicella) -> her profile: Family Law, Boca Raton, phone 561-928-3963 -> the Florida-wide Top 100 (first Jeffrey A. Baskies) and the women's list (first Amy B. Beller); Heather appears on neither.

Generated by make_verifiers.py (deterministic regeneration; do not edit by hand).
"""
from verify_lib import (check_answer_absent, check_answer_any, check_set_delta,
                        check_answer_count_at_least, check_answer_number,
                        check_answer_phrase, check_blocked, check_read_only,
                        check_rows_added, check_rows_changed, check_only_tables_changed,
                        check_rows_removed, check_screenshots,
                        check_trajectory_identity, check_visited_path,
                        final_answer, run_verifier)

TASK_ID = "Super Lawyers--5"


def run_checks(judge, traj, initial_db, after_db):
    answer = final_answer(traj)
    check_trajectory_identity(judge, traj, TASK_ID)
    check_screenshots(judge, traj)
    check_visited_path(judge, traj, "visited_fl_top_lists", r"/top-lists/florida/")
    check_visited_path(judge, traj, "visited_miami_top_100", r"/top-lists/florida/top-100-2026-miami-super-lawyers/")
    check_visited_path(judge, traj, "visited_apicella_profile", r"/lawyer/heather-l-apicella/")
    check_visited_path(judge, traj, "visited_fl_top_100", r"/top-lists/florida/top-100-2026-florida-super-lawyers/")
    check_visited_path(judge, traj, "visited_women_top_50", r"/top-lists/florida/top-50-2026-women-florida-super-lawyers/")
    check_answer_number(judge, answer, "answer_top100_count", 2)
    check_answer_phrase(judge, answer, "answer_womens_title", "Top 50: 2026 Women Florida Super Lawyers")
    check_answer_phrase(judge, answer, "answer_first_miami", "Heather L. Apicella")
    check_answer_phrase(judge, answer, "answer_practice_area", "Family Law")
    check_answer_phrase(judge, answer, "answer_office_city", "Boca Raton")
    check_answer_phrase(judge, answer, "answer_phone", "561-928-3963")
    check_answer_phrase(judge, answer, "answer_first_fl_top_100", "Jeffrey A. Baskies")
    check_answer_phrase(judge, answer, "answer_first_women", "Amy B. Beller")
    check_answer_any(judge, answer, "answer_on_either_list", ["does not appear on either", "not on either", "appears on neither", "neither list"])
    check_read_only(judge, initial_db, after_db)


if __name__ == "__main__":
    raise SystemExit(run_verifier(TASK_ID, run_checks))
