#!/usr/bin/env python3
"""Verify Super Lawyers--16.

Seattle criminal defense results -> the attorney whose practice-area chart shows 70 percent criminal defense while concentrating on DUI and white-collar work (Court Will) -> the three chart areas with exact percentages, first-admitted year, office phone.

Generated by make_verifiers.py (deterministic regeneration; do not edit by hand).
"""
from verify_lib import (check_answer_absent, check_answer_any, check_set_delta,
                        check_answer_count_at_least, check_answer_number,
                        check_answer_phrase, check_blocked, check_read_only,
                        check_rows_added, check_rows_changed, check_only_tables_changed,
                        check_rows_removed, check_screenshots,
                        check_trajectory_identity, check_visited_path,
                        final_answer, run_verifier)

TASK_ID = "Super Lawyers--16"


def run_checks(judge, traj, initial_db, after_db):
    answer = final_answer(traj)
    from reviewed_checks import check_answer
    check_answer(judge, traj, 16)
    check_trajectory_identity(judge, traj, TASK_ID)
    check_screenshots(judge, traj)
    check_visited_path(judge, traj, "visited_cd_seattle_serp", r"/attorneys/criminal-defense/washington/seattle/")
    check_visited_path(judge, traj, "visited_court_will_profile", r"/lawyer/court-will/")
    check_answer_phrase(judge, answer, "answer_attorney", "Court Will")
    check_answer_phrase(judge, answer, "answer_chart_1", "70% Criminal Defense")
    check_answer_any(judge, answer, "answer_chart_2", ["20% Criminal Defense: DUI/DWI", "20% DUI/DWI"])
    check_answer_any(judge, answer, "answer_chart_3", ["10% Criminal Defense: White Collar", "10% White Collar"])
    check_answer_phrase(judge, answer, "answer_first_admitted", "2003")
    check_answer_phrase(judge, answer, "answer_phone", "206-209-5585")
    check_read_only(judge, initial_db, after_db)


if __name__ == "__main__":
    raise SystemExit(run_verifier(TASK_ID, run_checks))
