#!/usr/bin/env python3
"""Verify Super Lawyers--3.

Clifford Law Offices firm profile -> 6 attorneys + office address -> open EACH attorney's profile -> the partner first admitted in 1976 (Robert A. Clifford, National Law Journal Lifetime Achievement), the most recently admitted partner (Bradley M. Cosgrove, 2006), and how many attorneys were first admitted in the 1980s (2: Kevin P. Durkin 1980, Keith A. Hebeisen 1983).

Generated by make_verifiers.py (deterministic regeneration; do not edit by hand).
"""
from verify_lib import (check_answer_absent, check_answer_any, check_set_delta,
                        check_answer_count_at_least, check_answer_number,
                        check_answer_phrase, check_blocked, check_read_only,
                        check_rows_added, check_rows_changed, check_only_tables_changed,
                        check_rows_removed, check_screenshots,
                        check_trajectory_identity, check_visited_path,
                        final_answer, run_verifier)

TASK_ID = "Super Lawyers--3"


def run_checks(judge, traj, initial_db, after_db):
    answer = final_answer(traj)
    check_trajectory_identity(judge, traj, TASK_ID)
    check_screenshots(judge, traj)
    check_visited_path(judge, traj, "visited_lawyer_search", r"/attorneys/search/")
    check_visited_path(judge, traj, "visited_firm_profile", r"/lawfirm/clifford-law-offices/")
    check_visited_path(judge, traj, "visited_robert_profile", r"/profiles/illinois/chicago/lawyer/robert-a-clifford/")
    check_visited_path(judge, traj, "visited_durkin_profile", r"/lawyer/kevin-p-durkin/")
    check_visited_path(judge, traj, "visited_hebeisen_profile", r"/lawyer/keith-a-hebeisen/")
    check_visited_path(judge, traj, "visited_capra_profile", r"/lawyer/susan-a-capra/")
    check_visited_path(judge, traj, "visited_mcnulty_profile", r"/lawyer/shannon-m-mcnulty/")
    check_visited_path(judge, traj, "visited_cosgrove_profile", r"/lawyer/bradley-m-cosgrove/")
    check_answer_number(judge, answer, "answer_firm_attorney_count", 6)
    check_answer_phrase(judge, answer, "answer_office_address", "120 North LaSalle Street")
    check_answer_phrase(judge, answer, "answer_partner", "Robert A. Clifford")
    check_answer_phrase(judge, answer, "answer_first_admitted", "1976")
    check_answer_phrase(judge, answer, "answer_nlj_honor", "National Law Journal")
    check_answer_phrase(judge, answer, "answer_lifetime_honor", "Lifetime Achievement")
    check_answer_phrase(judge, answer, "answer_recent_partner", "Bradley M. Cosgrove")
    check_answer_phrase(judge, answer, "answer_recent_partner_year", "2006")
    check_answer_number(judge, answer, "answer_eighties_count", 2)
    check_answer_count_at_least(judge, answer, "answer_eighties_names", ["Kevin P. Durkin", "Keith A. Hebeisen"], 2)
    check_read_only(judge, initial_db, after_db)


if __name__ == "__main__":
    raise SystemExit(run_verifier(TASK_ID, run_checks))
