#!/usr/bin/env python3
"""Verify Super Lawyers--14.

April Jones feature article 'Finding the After' -> published in 2026 Colorado Super Lawyers magazine by Amy White on March 19, 2026 -> wish list (cat, condo, convertible) -> Sam Cary Bar Association twice -> 2027 Colorado Bar Association president -> Jones Law Firm -> featured lawyer April D. Jones with office city Greenwood Village, CO (rendered by the r2 fix) -> related article 'Bump in the Road': subtitle asks who's liable over a pothole, features Daniel Flanzig (re-anchored; the r1 BLOCKED office-city fact is now rendered on the article page).

Generated by make_verifiers.py (deterministic regeneration; do not edit by hand).
"""
from verify_lib import (check_answer_absent, check_answer_any, check_set_delta,
                        check_answer_count_at_least, check_answer_number,
                        check_answer_phrase, check_blocked, check_read_only,
                        check_rows_added, check_rows_changed, check_only_tables_changed,
                        check_rows_removed, check_screenshots,
                        check_trajectory_identity, check_visited_path,
                        final_answer, run_verifier)

TASK_ID = "Super Lawyers--14"


def run_checks(judge, traj, initial_db, after_db):
    answer = final_answer(traj)
    from reviewed_checks import check_answer
    check_answer(judge, traj, 14)
    check_trajectory_identity(judge, traj, TASK_ID)
    check_screenshots(judge, traj)
    check_visited_path(judge, traj, "visited_articles_hub", r"/articles/")
    check_visited_path(judge, traj, "visited_article", r"/articles/colorado/finding-the-after/")
    check_answer_phrase(judge, answer, "answer_magazine", "Colorado Super Lawyers magazine")
    check_answer_phrase(judge, answer, "answer_author", "Amy White")
    check_answer_phrase(judge, answer, "answer_publication_date", "March 19, 2026")
    check_answer_count_at_least(judge, answer, "answer_wish_list", ["cat", "condo", "convertible"], 3)
    check_answer_phrase(judge, answer, "answer_bar_association", "Sam Cary Bar Association")
    check_answer_phrase(judge, answer, "answer_2027_role", "Colorado Bar Association")
    check_answer_phrase(judge, answer, "answer_firm", "Jones Law Firm")
    check_answer_phrase(judge, answer, "answer_featured_lawyer", "April D. Jones")
    check_answer_phrase(judge, answer, "answer_featured_city", "Greenwood Village, CO")
    check_read_only(judge, initial_db, after_db)


if __name__ == "__main__":
    raise SystemExit(run_verifier(TASK_ID, run_checks))
