#!/usr/bin/env python3
"""Verify Super Lawyers--11.

Legal article resources -> the elderly financial abuse article -> two warning signs -> the Ask a Lawyer Florida elder-financial-abuse question -> answering attorney name, city, phone.

Generated by make_verifiers.py (deterministic regeneration; do not edit by hand).
"""
from verify_lib import (check_answer_absent, check_answer_any, check_set_delta,
                        check_answer_count_at_least, check_answer_number,
                        check_answer_phrase, check_blocked, check_read_only,
                        check_rows_added, check_rows_changed, check_only_tables_changed,
                        check_rows_removed, check_screenshots,
                        check_trajectory_identity, check_visited_path,
                        final_answer, run_verifier)

TASK_ID = "Super Lawyers--11"


def run_checks(judge, traj, initial_db, after_db):
    answer = final_answer(traj)
    check_trajectory_identity(judge, traj, TASK_ID)
    check_screenshots(judge, traj)
    check_visited_path(judge, traj, "visited_resources_hub", r"/resources/")
    check_visited_path(judge, traj, "visited_elder_abuse_article", r"/resources/elder-law/what-is-elderly-financial-abuse/")
    check_visited_path(judge, traj, "visited_answers_hub", r"/answers/")
    check_visited_path(judge, traj, "visited_fl_answer", r"/answers/elder-law/florida/")
    check_answer_count_at_least(judge, answer, "answer_warning_signs", ["Large withdrawals", "changes in spending habits", "Someone the older person recently met", "undue influence", "Unpaid bills", "lottery", "telemarketing", "identity theft"], 2)
    check_answer_phrase(judge, answer, "answer_attorney", "Natasha Perez")
    check_answer_phrase(judge, answer, "answer_city", "Miami")
    check_answer_phrase(judge, answer, "answer_phone", "305-998-0051")
    check_read_only(judge, initial_db, after_db)


if __name__ == "__main__":
    raise SystemExit(run_verifier(TASK_ID, run_checks))
